/*----- PROTECTED REGION ID(LMCLoggerClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        LMCLoggerClass.h
//
// description : Include for the LMCLogger root class.
//               This class is the singleton class for
//                the LMCLogger device class.
//               It contains all properties and methods which the 
//               LMCLogger requires only once e.g. the commands.
//
// project :     LMCLogger
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef LMCLoggerClass_H
#define LMCLoggerClass_H

#include <tango.h>
#include <LMCLogger.h>


/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass.h


namespace LMCLogger_ns
{
/*----- PROTECTED REGION ID(LMCLoggerClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute syslog_level class definition
class syslog_levelAttrib: public Tango::Attr
{
public:
	syslog_levelAttrib():Attr("syslog_level",
			Tango::DEV_STRING, Tango::READ) {};
	~syslog_levelAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LMCLogger *>(dev))->read_syslog_level(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LMCLogger *>(dev))->is_syslog_level_allowed(ty);}
};

//	Attribute enable_logfw class definition
class enable_logfwAttrib: public Tango::Attr
{
public:
	enable_logfwAttrib():Attr("enable_logfw",
			Tango::DEV_SHORT, Tango::READ) {};
	~enable_logfwAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<LMCLogger *>(dev))->read_enable_logfw(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<LMCLogger *>(dev))->is_enable_logfw_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command log class definition
class logClass : public Tango::Command
{
public:
	logClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	logClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~logClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LMCLogger *>(dev))->is_log_allowed(any);}
};

//	Command SetFileLogLevel class definition
class SetFileLogLevelClass : public Tango::Command
{
public:
	SetFileLogLevelClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	SetFileLogLevelClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~SetFileLogLevelClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LMCLogger *>(dev))->is_SetFileLogLevel_allowed(any);}
};

//	Command SetDeviceLogLevel class definition
class SetDeviceLogLevelClass : public Tango::Command
{
public:
	SetDeviceLogLevelClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	SetDeviceLogLevelClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~SetDeviceLogLevelClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LMCLogger *>(dev))->is_SetDeviceLogLevel_allowed(any);}
};

//	Command SetConsoleLogLevel class definition
class SetConsoleLogLevelClass : public Tango::Command
{
public:
	SetConsoleLogLevelClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	SetConsoleLogLevelClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~SetConsoleLogLevelClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LMCLogger *>(dev))->is_SetConsoleLogLevel_allowed(any);}
};

//	Command SetSysLogLevel class definition
class SetSysLogLevelClass : public Tango::Command
{
public:
	SetSysLogLevelClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	SetSysLogLevelClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~SetSysLogLevelClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LMCLogger *>(dev))->is_SetSysLogLevel_allowed(any);}
};

//	Command EnableLogForward class definition
class EnableLogForwardClass : public Tango::Command
{
public:
	EnableLogForwardClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	EnableLogForwardClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~EnableLogForwardClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LMCLogger *>(dev))->is_EnableLogForward_allowed(any);}
};

//	Command TestLog class definition
class TestLogClass : public Tango::Command
{
public:
	TestLogClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	TestLogClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~TestLogClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<LMCLogger *>(dev))->is_TestLog_allowed(any);}
};


/**
 *	The LMCLoggerClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  LMCLoggerClass : public Tango::DeviceClass
#else
class LMCLoggerClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(LMCLoggerClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static LMCLoggerClass *init(const char *);
		static LMCLoggerClass *instance();
		~LMCLoggerClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		LMCLoggerClass(string &);
		static LMCLoggerClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	LMCLogger_H
