/*----- PROTECTED REGION ID(LMCLoggerClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        LMCLoggerClass.cpp
//
// description : C++ source for the LMCLoggerClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the LMCLogger once per process.
//
// project :     LMCLogger
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <LMCLoggerClass.h>

/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass.cpp

//-------------------------------------------------------------------
/**
 *	Create LMCLoggerClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_LMCLogger_class(const char *name) {
		return LMCLogger_ns::LMCLoggerClass::init(name);
	}
}

namespace LMCLogger_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
LMCLoggerClass *LMCLoggerClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		LMCLoggerClass::LMCLoggerClass(string &s)
 * description : 	constructor for the LMCLoggerClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
LMCLoggerClass::LMCLoggerClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering LMCLoggerClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(LMCLoggerClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass::constructor

	cout2 << "Leaving LMCLoggerClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		LMCLoggerClass::~LMCLoggerClass()
 * description : 	destructor for the LMCLoggerClass
 */
//--------------------------------------------------------
LMCLoggerClass::~LMCLoggerClass()
{
	/*----- PROTECTED REGION ID(LMCLoggerClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		LMCLoggerClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
LMCLoggerClass *LMCLoggerClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new LMCLoggerClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		LMCLoggerClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
LMCLoggerClass *LMCLoggerClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		logClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *logClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "logClass::execute(): arrived" << endl;
	const Tango::DevVarStringArray *argin;
	extract(in_any, argin);
	((static_cast<LMCLogger *>(device))->log(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetFileLogLevelClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetFileLogLevelClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetFileLogLevelClass::execute(): arrived" << endl;
	Tango::DevLong argin;
	extract(in_any, argin);
	((static_cast<LMCLogger *>(device))->set_file_log_level(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetDeviceLogLevelClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetDeviceLogLevelClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetDeviceLogLevelClass::execute(): arrived" << endl;
	Tango::DevLong argin;
	extract(in_any, argin);
	((static_cast<LMCLogger *>(device))->set_device_log_level(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetConsoleLogLevelClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetConsoleLogLevelClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetConsoleLogLevelClass::execute(): arrived" << endl;
	Tango::DevLong argin;
	extract(in_any, argin);
	((static_cast<LMCLogger *>(device))->set_console_log_level(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SetSysLogLevelClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetSysLogLevelClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetSysLogLevelClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	((static_cast<LMCLogger *>(device))->set_sys_log_level(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		EnableLogForwardClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *EnableLogForwardClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "EnableLogForwardClass::execute(): arrived" << endl;
	Tango::DevShort argin;
	extract(in_any, argin);
	((static_cast<LMCLogger *>(device))->enable_log_forward(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		TestLogClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *TestLogClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "TestLogClass::execute(): arrived" << endl;
	const Tango::DevVarLongStringArray *argin;
	extract(in_any, argin);
	((static_cast<LMCLogger *>(device))->test_log(argin));
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : LMCLoggerClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum LMCLoggerClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : LMCLoggerClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum LMCLoggerClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : LMCLoggerClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum LMCLoggerClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : LMCLoggerClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void LMCLoggerClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "syslog_facility";
	prop_desc = "LOG_USER: A miscellaneous user process\nLOG_MAIL: Mail\nLOG_DAEMON: A miscellaneous system daemon\nLOG_AUTH:  Security (authorization)\nLOG_SYSLOG: Syslog\nLOG_LPR: Central printer\nLOG_NEWS: Network news (e.g. Usenet)\nLOG_UUCP: UUCP\nLOG_CRON: Cron and At\nLOG_AUTHPRIV: Private security (authorization)\nLOG_FTP: Ftp server\nLOG_LOCAL0,1,2,3,4,5,6,7: Locally defined\n\n``auth``: LOG_AUTH\n``authpriv``: LOG_AUTHPRIV\n``cron``: LOG_CRON \n``daemon``: LOG_DAEMON\n``ftp``: LOG_FTP\n``kern``: LOG_KERN\n``lpr``: LOG_LPR\n``mail``: LOG_MAIL\n``mark``: INTERNAL_MARK\n``news``: LOG_NEWS\n``security``: LOG_AUTH,\n``syslog``: LOG_SYSLOG\n``user``: LOG_USER\n``uucp``: LOG_UUCP\n``local0``: LOG_LOCAL0\n``local1``: LOG_LOCAL1 \n``local2``: LOG_LOCAL2 \n``local3``: LOG_LOCAL3 \n``local4``: LOG_LOCAL4 \n``local5``: LOG_LOCAL5 \n``local6``: LOG_LOCAL6 \n``local7``: LOG_LOCAL7";
	prop_def  = "local6";
	vect_data.clear();
	vect_data.push_back("local6");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "default_syslog_level";
	prop_desc = "Default log level to be used at startup for logging to syslog";
	prop_def  = "OFF";
	vect_data.clear();
	vect_data.push_back("OFF");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "startup_enable_logfw";
	prop_desc = "Enable log forwarding";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "syslog_logger";
	prop_desc = "SysLog library to be used:\n\n1=LOG4CXX\n2=BOOST";
	prop_def  = "1";
	vect_data.clear();
	vect_data.push_back("1");
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : LMCLoggerClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void LMCLoggerClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("LMCLogger");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("LMCLogger device server");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("LMCLogger");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : LMCLoggerClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void LMCLoggerClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(LMCLoggerClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new LMCLogger(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		LMCLogger *dev = static_cast<LMCLogger *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(LMCLoggerClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : LMCLoggerClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void LMCLoggerClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(LMCLoggerClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass::attribute_factory_before
	//	Attribute : syslog_level
	syslog_levelAttrib	*syslog_level = new syslog_levelAttrib();
	Tango::UserDefaultAttrProp	syslog_level_prop;
	syslog_level_prop.set_description("Log level used for logging to syslog (OFF,TRACE,DEBUG,INFO,WARN,ERROR,FATAL)");
	syslog_level_prop.set_label("syslog_level");
	//	unit	not set for syslog_level
	//	standard_unit	not set for syslog_level
	//	display_unit	not set for syslog_level
	//	format	not set for syslog_level
	//	max_value	not set for syslog_level
	//	min_value	not set for syslog_level
	//	max_alarm	not set for syslog_level
	//	min_alarm	not set for syslog_level
	//	max_warning	not set for syslog_level
	//	min_warning	not set for syslog_level
	//	delta_t	not set for syslog_level
	//	delta_val	not set for syslog_level
	
	syslog_level->set_default_properties(syslog_level_prop);
	//	Not Polled
	syslog_level->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(syslog_level);

	//	Attribute : enable_logfw
	enable_logfwAttrib	*enable_logfw = new enable_logfwAttrib();
	Tango::UserDefaultAttrProp	enable_logfw_prop;
	enable_logfw_prop.set_description("Flag signalling if log forwarding is active/inactive");
	//	label	not set for enable_logfw
	//	unit	not set for enable_logfw
	//	standard_unit	not set for enable_logfw
	//	display_unit	not set for enable_logfw
	//	format	not set for enable_logfw
	//	max_value	not set for enable_logfw
	//	min_value	not set for enable_logfw
	//	max_alarm	not set for enable_logfw
	//	min_alarm	not set for enable_logfw
	//	max_warning	not set for enable_logfw
	//	min_warning	not set for enable_logfw
	//	delta_t	not set for enable_logfw
	//	delta_val	not set for enable_logfw
	
	enable_logfw->set_default_properties(enable_logfw_prop);
	//	Not Polled
	enable_logfw->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(enable_logfw);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(LMCLoggerClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : LMCLoggerClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void LMCLoggerClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(LMCLoggerClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass::pipe_factory_before
	/*----- PROTECTED REGION ID(LMCLoggerClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : LMCLoggerClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void LMCLoggerClass::command_factory()
{
	/*----- PROTECTED REGION ID(LMCLoggerClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass::command_factory_before


	//	Command log
	logClass	*plogCmd =
		new logClass("log",
			Tango::DEVVAR_STRINGARRAY, Tango::DEV_VOID,
			"Logging info received from emitter devices",
			"",
			Tango::OPERATOR);
	command_list.push_back(plogCmd);

	//	Command SetFileLogLevel
	SetFileLogLevelClass	*pSetFileLogLevelCmd =
		new SetFileLogLevelClass("SetFileLogLevel",
			Tango::DEV_LONG, Tango::DEV_VOID,
			"The requested log level\n(0=OFF, 1=FATAL, 2=ERROR, 3=WARNING, 4=INFO, 5=DEBUG)",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetFileLogLevelCmd);

	//	Command SetDeviceLogLevel
	SetDeviceLogLevelClass	*pSetDeviceLogLevelCmd =
		new SetDeviceLogLevelClass("SetDeviceLogLevel",
			Tango::DEV_LONG, Tango::DEV_VOID,
			"The requested log level\n(0=OFF, 1=FATAL, 2=ERROR, 3=WARNING, 4=INFO, 5=DEBUG)",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetDeviceLogLevelCmd);

	//	Command SetConsoleLogLevel
	SetConsoleLogLevelClass	*pSetConsoleLogLevelCmd =
		new SetConsoleLogLevelClass("SetConsoleLogLevel",
			Tango::DEV_LONG, Tango::DEV_VOID,
			"The requested log level\n(0=OFF, 1=FATAL, 2=ERROR, 3=WARNING, 4=INFO, 5=DEBUG)",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetConsoleLogLevelCmd);

	//	Command SetSysLogLevel
	SetSysLogLevelClass	*pSetSysLogLevelCmd =
		new SetSysLogLevelClass("SetSysLogLevel",
			Tango::DEV_STRING, Tango::DEV_VOID,
			"The requested log level\n(0=OFF, 1=FATAL, 2=ERROR, 3=WARNING, 4=INFO, 5=DEBUG)",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSetSysLogLevelCmd);

	//	Command EnableLogForward
	EnableLogForwardClass	*pEnableLogForwardCmd =
		new EnableLogForwardClass("EnableLogForward",
			Tango::DEV_SHORT, Tango::DEV_VOID,
			"0=disable\n1=enable",
			"",
			Tango::OPERATOR);
	command_list.push_back(pEnableLogForwardCmd);

	//	Command TestLog
	TestLogClass	*pTestLogCmd =
		new TestLogClass("TestLog",
			Tango::DEVVAR_LONGSTRINGARRAY, Tango::DEV_VOID,
			"Long arg\n[0]: Level of log message\n(0=OFF, 1=FATAL, 2=ERROR, 3=WARNING, 4=INFO, 5=DEBUG)\n\nString arg\n[0]: log message",
			"",
			Tango::OPERATOR);
	command_list.push_back(pTestLogCmd);

	/*----- PROTECTED REGION ID(LMCLoggerClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		LMCLoggerClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void LMCLoggerClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(LMCLoggerClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		LMCLoggerClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void LMCLoggerClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		LMCLogger *dev = static_cast<LMCLogger *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(LMCLoggerClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : LMCLoggerClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *LMCLoggerClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(LMCLoggerClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	LMCLoggerClass::Additional Methods
} //	namespace
