/*----- PROTECTED REGION ID(LMCInterfaceStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        LMCInterfaceStateMachine.cpp
//
// description : State machine file for the LMCInterface class
//
// project :     LMC Interface
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <LMCInterface.h>

/*----- PROTECTED REGION END -----*/	//	LMCInterface::LMCInterfaceStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace LMCInterface_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : LMCInterface::is_echo_allowed()
 *	Description : Execution allowed for echo attribute
 */
//--------------------------------------------------------
bool LMCInterface::is_echo_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for echo command.
	/*----- PROTECTED REGION ID(LMCInterface::echoStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LMCInterface::echoStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LMCInterface::is_Revoke_allowed()
 *	Description : Execution allowed for Revoke attribute
 */
//--------------------------------------------------------
bool LMCInterface::is_Revoke_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Revoke command.
	/*----- PROTECTED REGION ID(LMCInterface::RevokeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LMCInterface::RevokeStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : LMCInterface::is_FlushCommandQueue_allowed()
 *	Description : Execution allowed for FlushCommandQueue attribute
 */
//--------------------------------------------------------
bool LMCInterface::is_FlushCommandQueue_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for FlushCommandQueue command.
	/*----- PROTECTED REGION ID(LMCInterface::FlushCommandQueueStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	LMCInterface::FlushCommandQueueStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(LMCInterface::LMCInterfaceStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	LMCInterface::LMCInterfaceStateAllowed.AdditionalMethods

}	//	End of namespace
