/*----- PROTECTED REGION ID(RxEmulatorStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        RxEmulatorStateMachine.cpp
//
// description : State machine file for the RxEmulator class
//
// project :     RxEmulator
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <RxEmulator.h>

/*----- PROTECTED REGION END -----*/	//	RxEmulator::RxEmulatorStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace RxEmulator_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_attenuation_allowed()
 *	Description : Execution allowed for attenuation attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_attenuation_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for attenuation attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::attenuationStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::attenuationStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_b1_capabilityState_allowed()
 *	Description : Execution allowed for b1_capabilityState attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_b1_capabilityState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for b1_capabilityState attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::b1_capabilityStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::b1_capabilityStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_b1_samplingClock_allowed()
 *	Description : Execution allowed for b1_samplingClock attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_b1_samplingClock_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for b1_samplingClock attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::b1_samplingClockStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::b1_samplingClockStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_b1_synchronisedClock_allowed()
 *	Description : Execution allowed for b1_synchronisedClock attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_b1_synchronisedClock_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for b1_synchronisedClock attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::b1_synchronisedClockStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::b1_synchronisedClockStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_b2_capabilityState_allowed()
 *	Description : Execution allowed for b2_capabilityState attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_b2_capabilityState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for b2_capabilityState attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::b2_capabilityStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::b2_capabilityStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_b2_samplingClock_allowed()
 *	Description : Execution allowed for b2_samplingClock attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_b2_samplingClock_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for b2_samplingClock attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::b2_samplingClockStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::b2_samplingClockStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_b2_synchronisedClock_allowed()
 *	Description : Execution allowed for b2_synchronisedClock attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_b2_synchronisedClock_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for b2_synchronisedClock attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::b2_synchronisedClockStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::b2_synchronisedClockStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_b3_capabilityState_allowed()
 *	Description : Execution allowed for b3_capabilityState attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_b3_capabilityState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for b3_capabilityState attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::b3_capabilityStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::b3_capabilityStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_b3_samplingClock_allowed()
 *	Description : Execution allowed for b3_samplingClock attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_b3_samplingClock_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for b3_samplingClock attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::b3_samplingClockStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::b3_samplingClockStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_b3_synchronisedClock_allowed()
 *	Description : Execution allowed for b3_synchronisedClock attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_b3_synchronisedClock_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for b3_synchronisedClock attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::b3_synchronisedClockStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::b3_synchronisedClockStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_b4_capabilityState_allowed()
 *	Description : Execution allowed for b4_capabilityState attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_b4_capabilityState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for b4_capabilityState attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::b4_capabilityStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::b4_capabilityStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_b4_samplingClock_allowed()
 *	Description : Execution allowed for b4_samplingClock attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_b4_samplingClock_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for b4_samplingClock attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::b4_samplingClockStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::b4_samplingClockStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_b4_synchronisedClock_allowed()
 *	Description : Execution allowed for b4_synchronisedClock attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_b4_synchronisedClock_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for b4_synchronisedClock attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::b4_synchronisedClockStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::b4_synchronisedClockStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_b5_capabilityState_allowed()
 *	Description : Execution allowed for b5_capabilityState attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_b5_capabilityState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for b5_capabilityState attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::b5_capabilityStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::b5_capabilityStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_b5_samplingClock_allowed()
 *	Description : Execution allowed for b5_samplingClock attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_b5_samplingClock_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for b5_samplingClock attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::b5_samplingClockStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::b5_samplingClockStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_b5_synchronisedClock_allowed()
 *	Description : Execution allowed for b5_synchronisedClock attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_b5_synchronisedClock_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for b5_synchronisedClock attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::b5_synchronisedClockStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::b5_synchronisedClockStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_noisesource_offTime_allowed()
 *	Description : Execution allowed for noisesource_offTime attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_noisesource_offTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for noisesource_offTime attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::noisesource_offTimeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::noisesource_offTimeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_noisesource_onTime_allowed()
 *	Description : Execution allowed for noisesource_onTime attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_noisesource_onTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for noisesource_onTime attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::noisesource_onTimeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::noisesource_onTimeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_noisesource_period_allowed()
 *	Description : Execution allowed for noisesource_period attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_noisesource_period_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for noisesource_period attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::noisesource_periodStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::noisesource_periodStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_noisesource_startTime_allowed()
 *	Description : Execution allowed for noisesource_startTime attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_noisesource_startTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for noisesource_startTime attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::noisesource_startTimeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::noisesource_startTimeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rx_fwVersions_allowed()
 *	Description : Execution allowed for rx_fwVersions attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rx_fwVersions_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rx_fwVersions attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rx_fwVersionsStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rx_fwVersionsStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rx_healthState_allowed()
 *	Description : Execution allowed for rx_healthState attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rx_healthState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rx_healthState attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rx_healthStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rx_healthStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rx_mode_allowed()
 *	Description : Execution allowed for rx_mode attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rx_mode_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rx_mode attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rx_modeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rx_modeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rx_powerState_allowed()
 *	Description : Execution allowed for rx_powerState attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rx_powerState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rx_powerState attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rx_powerStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rx_powerStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rx_protocolVersion_allowed()
 *	Description : Execution allowed for rx_protocolVersion attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rx_protocolVersion_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rx_protocolVersion attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rx_protocolVersionStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rx_protocolVersionStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rx_serialNumbers_allowed()
 *	Description : Execution allowed for rx_serialNumbers attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rx_serialNumbers_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rx_serialNumbers attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rx_serialNumbersStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rx_serialNumbersStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rx_swVersions_allowed()
 *	Description : Execution allowed for rx_swVersions attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rx_swVersions_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rx_swVersions attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rx_swVersionsStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rx_swVersionsStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxpu_expectedOnline_allowed()
 *	Description : Execution allowed for rxpu_expectedOnline attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxpu_expectedOnline_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxpu_expectedOnline attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxpu_expectedOnlineStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxpu_expectedOnlineStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxpu_healthState_allowed()
 *	Description : Execution allowed for rxpu_healthState attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxpu_healthState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxpu_healthState attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxpu_healthStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxpu_healthStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxpu_hourCounter_allowed()
 *	Description : Execution allowed for rxpu_hourCounter attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxpu_hourCounter_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxpu_hourCounter attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxpu_hourCounterStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxpu_hourCounterStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxpu_operationalTime_allowed()
 *	Description : Execution allowed for rxpu_operationalTime attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxpu_operationalTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxpu_operationalTime attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxpu_operationalTimeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxpu_operationalTimeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxpu_supplyCurrent_allowed()
 *	Description : Execution allowed for rxpu_supplyCurrent attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxpu_supplyCurrent_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxpu_supplyCurrent attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxpu_supplyCurrentStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxpu_supplyCurrentStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxpu_supplyVoltage_allowed()
 *	Description : Execution allowed for rxpu_supplyVoltage attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxpu_supplyVoltage_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxpu_supplyVoltage attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxpu_supplyVoltageStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxpu_supplyVoltageStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxpu_temperature_allowed()
 *	Description : Execution allowed for rxpu_temperature attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxpu_temperature_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxpu_temperature attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxpu_temperatureStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxpu_temperatureStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs123_adcPower_allowed()
 *	Description : Execution allowed for rxs123_adcPower attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs123_adcPower_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs123_adcPower attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs123_adcPowerStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs123_adcPowerStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs123_adcVariance_allowed()
 *	Description : Execution allowed for rxs123_adcVariance attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs123_adcVariance_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs123_adcVariance attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs123_adcVarianceStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs123_adcVarianceStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs123_expectedOnline_allowed()
 *	Description : Execution allowed for rxs123_expectedOnline attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs123_expectedOnline_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs123_expectedOnline attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs123_expectedOnlineStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs123_expectedOnlineStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs123_healthState_allowed()
 *	Description : Execution allowed for rxs123_healthState attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs123_healthState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs123_healthState attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs123_healthStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs123_healthStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs123_hourCounter_allowed()
 *	Description : Execution allowed for rxs123_hourCounter attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs123_hourCounter_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs123_hourCounter attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs123_hourCounterStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs123_hourCounterStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs123_operationalTime_allowed()
 *	Description : Execution allowed for rxs123_operationalTime attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs123_operationalTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs123_operationalTime attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs123_operationalTimeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs123_operationalTimeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs123_supplyCurrent_allowed()
 *	Description : Execution allowed for rxs123_supplyCurrent attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs123_supplyCurrent_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs123_supplyCurrent attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs123_supplyCurrentStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs123_supplyCurrentStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs123_supplyVoltage_allowed()
 *	Description : Execution allowed for rxs123_supplyVoltage attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs123_supplyVoltage_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs123_supplyVoltage attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs123_supplyVoltageStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs123_supplyVoltageStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs123_temperature_allowed()
 *	Description : Execution allowed for rxs123_temperature attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs123_temperature_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs123_temperature attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs123_temperatureStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs123_temperatureStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs45_adcPower_allowed()
 *	Description : Execution allowed for rxs45_adcPower attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs45_adcPower_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs45_adcPower attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs45_adcPowerStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs45_adcPowerStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs45_adcVariance_allowed()
 *	Description : Execution allowed for rxs45_adcVariance attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs45_adcVariance_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs45_adcVariance attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs45_adcVarianceStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs45_adcVarianceStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs45_expectedOnline_allowed()
 *	Description : Execution allowed for rxs45_expectedOnline attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs45_expectedOnline_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs45_expectedOnline attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs45_expectedOnlineStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs45_expectedOnlineStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs45_healthState_allowed()
 *	Description : Execution allowed for rxs45_healthState attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs45_healthState_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs45_healthState attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs45_healthStateStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs45_healthStateStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs45_hourCounter_allowed()
 *	Description : Execution allowed for rxs45_hourCounter attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs45_hourCounter_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs45_hourCounter attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs45_hourCounterStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs45_hourCounterStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs45_supplyCurrent_allowed()
 *	Description : Execution allowed for rxs45_supplyCurrent attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs45_supplyCurrent_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs45_supplyCurrent attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs45_supplyCurrentStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs45_supplyCurrentStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs45_supplyVoltage_allowed()
 *	Description : Execution allowed for rxs45_supplyVoltage attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs45_supplyVoltage_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs45_supplyVoltage attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs45_supplyVoltageStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs45_supplyVoltageStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_rxs45_temperature_allowed()
 *	Description : Execution allowed for rxs45_temperature attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_rxs45_temperature_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for rxs45_temperature attribute in read access.
	/*----- PROTECTED REGION ID(RxEmulator::rxs45_temperatureStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::rxs45_temperatureStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_Capture_allowed()
 *	Description : Execution allowed for Capture attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_Capture_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Capture command.
	/*----- PROTECTED REGION ID(RxEmulator::CaptureStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::CaptureStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_ConfigureBand_allowed()
 *	Description : Execution allowed for ConfigureBand attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_ConfigureBand_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for ConfigureBand command.
	/*----- PROTECTED REGION ID(RxEmulator::ConfigureBandStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::ConfigureBandStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_SetEngineeringInterface_allowed()
 *	Description : Execution allowed for SetEngineeringInterface attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_SetEngineeringInterface_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for SetEngineeringInterface command.
	/*----- PROTECTED REGION ID(RxEmulator::SetEngineeringInterfaceStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::SetEngineeringInterfaceStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_SetExpectedOnline_allowed()
 *	Description : Execution allowed for SetExpectedOnline attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_SetExpectedOnline_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for SetExpectedOnline command.
	/*----- PROTECTED REGION ID(RxEmulator::SetExpectedOnlineStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::SetExpectedOnlineStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_SetSubElementMode_allowed()
 *	Description : Execution allowed for SetSubElementMode attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_SetSubElementMode_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for SetSubElementMode command.
	/*----- PROTECTED REGION ID(RxEmulator::SetSubElementModeStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::SetSubElementModeStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_SetNoiseSource_allowed()
 *	Description : Execution allowed for SetNoiseSource attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_SetNoiseSource_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for SetNoiseSource command.
	/*----- PROTECTED REGION ID(RxEmulator::SetNoiseSourceStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::SetNoiseSourceStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_Synchronise_allowed()
 *	Description : Execution allowed for Synchronise attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_Synchronise_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Synchronise command.
	/*----- PROTECTED REGION ID(RxEmulator::SynchroniseStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::SynchroniseStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulator::is_SetAttenuation_allowed()
 *	Description : Execution allowed for SetAttenuation attribute
 */
//--------------------------------------------------------
bool RxEmulator::is_SetAttenuation_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for SetAttenuation command.
	/*----- PROTECTED REGION ID(RxEmulator::SetAttenuationStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulator::SetAttenuationStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(RxEmulator::RxEmulatorStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	RxEmulator::RxEmulatorStateAllowed.AdditionalMethods

}	//	End of namespace
