/*----- PROTECTED REGION ID(RxEmulatorClass.cpp) ENABLED START -----*/
static const char *RcsId      = "$Id:  $";
static const char *TagName    = "$Name:  $";
static const char *CvsPath    = "$Source:  $";
static const char *SvnPath    = "$HeadURL:  $";
static const char *HttpServer = "http://www.esrf.eu/computing/cs/tango/tango_doc/ds_doc/";
//=============================================================================
//
// file :        RxEmulatorClass.cpp
//
// description : C++ source for the RxEmulatorClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the RxEmulator once per process.
//
// project :     RxEmulator
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <RxEmulatorClass.h>

/*----- PROTECTED REGION END -----*/	//	RxEmulatorClass.cpp

//-------------------------------------------------------------------
/**
 *	Create RxEmulatorClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_RxEmulator_class(const char *name) {
		return RxEmulator_ns::RxEmulatorClass::init(name);
	}
}

namespace RxEmulator_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
RxEmulatorClass *RxEmulatorClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		RxEmulatorClass::RxEmulatorClass(string &s)
 * description : 	constructor for the RxEmulatorClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
RxEmulatorClass::RxEmulatorClass(string &s):SEEmulatorBase_ns::SEEmulatorBaseClass(s)
{
	cout2 << "Entering RxEmulatorClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(RxEmulatorClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulatorClass::constructor

	cout2 << "Leaving RxEmulatorClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		RxEmulatorClass::~RxEmulatorClass()
 * description : 	destructor for the RxEmulatorClass
 */
//--------------------------------------------------------
RxEmulatorClass::~RxEmulatorClass()
{
	/*----- PROTECTED REGION ID(RxEmulatorClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulatorClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		RxEmulatorClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
RxEmulatorClass *RxEmulatorClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new RxEmulatorClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		RxEmulatorClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
RxEmulatorClass *RxEmulatorClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		CaptureClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *CaptureClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "CaptureClass::execute(): arrived" << endl;
	Tango::DevShort argin;
	extract(in_any, argin);
	return insert((static_cast<RxEmulator *>(device))->capture(argin));
}

//--------------------------------------------------------
/**
 * method : 		ConfigureBandClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ConfigureBandClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "ConfigureBandClass::execute(): arrived" << endl;
	Tango::DevShort argin;
	extract(in_any, argin);
	return insert((static_cast<RxEmulator *>(device))->configure_band(argin));
}

//--------------------------------------------------------
/**
 * method : 		SetEngineeringInterfaceClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetEngineeringInterfaceClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "SetEngineeringInterfaceClass::execute(): arrived" << endl;
	return insert((static_cast<RxEmulator *>(device))->set_engineering_interface());
}

//--------------------------------------------------------
/**
 * method : 		SetExpectedOnlineClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetExpectedOnlineClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetExpectedOnlineClass::execute(): arrived" << endl;
	const Tango::DevVarShortArray *argin;
	extract(in_any, argin);
	return insert((static_cast<RxEmulator *>(device))->set_expected_online(argin));
}

//--------------------------------------------------------
/**
 * method : 		SetSubElementModeClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetSubElementModeClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetSubElementModeClass::execute(): arrived" << endl;
	Tango::DevEnum argin;
	extract(in_any, argin);
	return insert((static_cast<RxEmulator *>(device))->set_sub_element_mode(argin));
}

//--------------------------------------------------------
/**
 * method : 		SetNoiseSourceClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetNoiseSourceClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetNoiseSourceClass::execute(): arrived" << endl;
	const Tango::DevVarLongArray *argin;
	extract(in_any, argin);
	return insert((static_cast<RxEmulator *>(device))->set_noise_source(argin));
}

//--------------------------------------------------------
/**
 * method : 		SynchroniseClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SynchroniseClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "SynchroniseClass::execute(): arrived" << endl;
	return insert((static_cast<RxEmulator *>(device))->synchronise());
}

//--------------------------------------------------------
/**
 * method : 		SetAttenuationClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SetAttenuationClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SetAttenuationClass::execute(): arrived" << endl;
	Tango::DevLong argin;
	extract(in_any, argin);
	return insert((static_cast<RxEmulator *>(device))->set_attenuation(argin));
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : RxEmulatorClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum RxEmulatorClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulatorClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum RxEmulatorClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulatorClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum RxEmulatorClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : RxEmulatorClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void RxEmulatorClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulatorClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void RxEmulatorClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("RxEmulator");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("Class emulating LMC-Rx interface");
	description << str_desc;
	data.push_back(description);

	//	put cvs or svn location
	string	filename("RxEmulator");
	filename += "Class.cpp";

	// check for cvs information
	string	src_path(CvsPath);
	start = src_path.find("/");
	if (start!=string::npos)
	{
		end   = src_path.find(filename);
		if (end>start)
		{
			string	strloc = src_path.substr(start, end-start);
			//	Check if specific repository
			start = strloc.find("/cvsroot/");
			if (start!=string::npos && start>0)
			{
				string	repository = strloc.substr(0, start);
				if (repository.find("/segfs/")!=string::npos)
					strloc = "ESRF:" + strloc.substr(start, strloc.length()-start);
			}
			Tango::DbDatum	cvs_loc("cvs_location");
			cvs_loc << strloc;
			data.push_back(cvs_loc);
		}
	}

	// check for svn information
	else
	{
		string	src_path(SvnPath);
		start = src_path.find("://");
		if (start!=string::npos)
		{
			end = src_path.find(filename);
			if (end>start)
			{
				header = "$HeadURL: ";
				start = header.length();
				string	strloc = src_path.substr(start, (end-start));
				
				Tango::DbDatum	svn_loc("svn_location");
				svn_loc << strloc;
				data.push_back(svn_loc);
			}
		}
	}

	//	Get CVS or SVN revision tag
	
	// CVS tag
	string	tagname(TagName);
	header = "$Name: ";
	start = header.length();
	string	endstr(" $");
	
	end   = tagname.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strtag = tagname.substr(start, end-start);
		Tango::DbDatum	cvs_tag("cvs_tag");
		cvs_tag << strtag;
		data.push_back(cvs_tag);
	}
	
	// SVN tag
	string	svnpath(SvnPath);
	header = "$HeadURL: ";
	start = header.length();
	
	end   = svnpath.find(endstr);
	if (end!=string::npos && end>start)
	{
		string	strloc = svnpath.substr(start, end-start);
		
		string tagstr ("/tags/");
		start = strloc.find(tagstr);
		if ( start!=string::npos )
		{
			start = start + tagstr.length();
			end   = strloc.find(filename);
			string	strtag = strloc.substr(start, end-start-1);
			
			Tango::DbDatum	svn_tag("svn_tag");
			svn_tag << strtag;
			data.push_back(svn_tag);
		}
	}

	//	Get URL location
	string	httpServ(HttpServer);
	if (httpServ.length()>0)
	{
		Tango::DbDatum	db_doc_url("doc_url");
		db_doc_url << httpServ;
		data.push_back(db_doc_url);
	}

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : RxEmulatorClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void RxEmulatorClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(RxEmulatorClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulatorClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new RxEmulator(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		RxEmulator *dev = static_cast<RxEmulator *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(RxEmulatorClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulatorClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : RxEmulatorClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void RxEmulatorClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(RxEmulatorClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulatorClass::attribute_factory_before
	//	Call atribute_factory for inherited class
	SEEmulatorBase_ns::SEEmulatorBaseClass::attribute_factory(att_list);

	//	Attribute : attenuation
	attenuationAttrib	*attenuation = new attenuationAttrib();
	Tango::UserDefaultAttrProp	attenuation_prop;
	attenuation_prop.set_description("Overall device attenuation. Default and persistence.");
	//	label	not set for attenuation
	attenuation_prop.set_unit("dB");
	//	standard_unit	not set for attenuation
	//	display_unit	not set for attenuation
	//	format	not set for attenuation
	//	max_value	not set for attenuation
	//	min_value	not set for attenuation
	//	max_alarm	not set for attenuation
	//	min_alarm	not set for attenuation
	//	max_warning	not set for attenuation
	//	min_warning	not set for attenuation
	//	delta_t	not set for attenuation
	//	delta_val	not set for attenuation
	attenuation_prop.set_event_period("3000");
	
	attenuation->set_default_properties(attenuation_prop);
	attenuation->set_polling_period(3000);
	attenuation->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	attenuation->set_change_event(true, false);
	att_list.push_back(attenuation);

	//	Attribute : b1_capabilityState
	b1_capabilityStateAttrib	*b1_capabilitystate = new b1_capabilityStateAttrib();
	Tango::UserDefaultAttrProp	b1_capabilitystate_prop;
	b1_capabilitystate_prop.set_description("Band capability state");
	//	label	not set for b1_capabilityState
	//	unit	not set for b1_capabilityState
	//	standard_unit	not set for b1_capabilityState
	//	display_unit	not set for b1_capabilityState
	//	format	not set for b1_capabilityState
	//	max_value	not set for b1_capabilityState
	//	min_value	not set for b1_capabilityState
	//	max_alarm	not set for b1_capabilityState
	//	min_alarm	not set for b1_capabilityState
	//	max_warning	not set for b1_capabilityState
	//	min_warning	not set for b1_capabilityState
	//	delta_t	not set for b1_capabilityState
	//	delta_val	not set for b1_capabilityState
	b1_capabilitystate_prop.set_event_rel_change("0.1");
	b1_capabilitystate_prop.set_event_abs_change("0.1");
	
	{
		vector<string> labels;
		labels.push_back("UNAVAILABLE");
		labels.push_back("STANDBY");
		labels.push_back("OPERATE");
		labels.push_back("CONFIGURE");
		b1_capabilitystate_prop.set_enum_labels(labels);
	}
	b1_capabilitystate->set_default_properties(b1_capabilitystate_prop);
	//	Not Polled
	b1_capabilitystate->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	b1_capabilitystate->set_change_event(true, false);
	att_list.push_back(b1_capabilitystate);

	//	Attribute : b1_samplingClock
	b1_samplingClockAttrib	*b1_samplingclock = new b1_samplingClockAttrib();
	Tango::UserDefaultAttrProp	b1_samplingclock_prop;
	b1_samplingclock_prop.set_description("Band sampling clock frequency in Hertz");
	//	label	not set for b1_samplingClock
	b1_samplingclock_prop.set_unit("Hz");
	//	standard_unit	not set for b1_samplingClock
	//	display_unit	not set for b1_samplingClock
	//	format	not set for b1_samplingClock
	//	max_value	not set for b1_samplingClock
	//	min_value	not set for b1_samplingClock
	//	max_alarm	not set for b1_samplingClock
	//	min_alarm	not set for b1_samplingClock
	//	max_warning	not set for b1_samplingClock
	//	min_warning	not set for b1_samplingClock
	//	delta_t	not set for b1_samplingClock
	//	delta_val	not set for b1_samplingClock
	b1_samplingclock_prop.set_event_period("3000");
	
	b1_samplingclock->set_default_properties(b1_samplingclock_prop);
	b1_samplingclock->set_polling_period(3000);
	b1_samplingclock->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	b1_samplingclock->set_change_event(true, false);
	att_list.push_back(b1_samplingclock);

	//	Attribute : b1_synchronisedClock
	b1_synchronisedClockAttrib	*b1_synchronisedclock = new b1_synchronisedClockAttrib();
	Tango::UserDefaultAttrProp	b1_synchronisedclock_prop;
	b1_synchronisedclock_prop.set_description("Band clock synchronised to TFR. \nNormally a boolean flag, but CHANGE_EVENT cannot be defined for boolean data types.");
	//	label	not set for b1_synchronisedClock
	//	unit	not set for b1_synchronisedClock
	//	standard_unit	not set for b1_synchronisedClock
	//	display_unit	not set for b1_synchronisedClock
	//	format	not set for b1_synchronisedClock
	//	max_value	not set for b1_synchronisedClock
	//	min_value	not set for b1_synchronisedClock
	//	max_alarm	not set for b1_synchronisedClock
	//	min_alarm	not set for b1_synchronisedClock
	//	max_warning	not set for b1_synchronisedClock
	//	min_warning	not set for b1_synchronisedClock
	//	delta_t	not set for b1_synchronisedClock
	//	delta_val	not set for b1_synchronisedClock
	b1_synchronisedclock_prop.set_event_rel_change("0.1");
	b1_synchronisedclock_prop.set_event_abs_change("0.1");
	
	b1_synchronisedclock->set_default_properties(b1_synchronisedclock_prop);
	b1_synchronisedclock->set_polling_period(3000);
	b1_synchronisedclock->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	b1_synchronisedclock->set_change_event(true, false);
	att_list.push_back(b1_synchronisedclock);

	//	Attribute : b2_capabilityState
	b2_capabilityStateAttrib	*b2_capabilitystate = new b2_capabilityStateAttrib();
	Tango::UserDefaultAttrProp	b2_capabilitystate_prop;
	b2_capabilitystate_prop.set_description("Band capability state");
	//	label	not set for b2_capabilityState
	//	unit	not set for b2_capabilityState
	//	standard_unit	not set for b2_capabilityState
	//	display_unit	not set for b2_capabilityState
	//	format	not set for b2_capabilityState
	//	max_value	not set for b2_capabilityState
	//	min_value	not set for b2_capabilityState
	//	max_alarm	not set for b2_capabilityState
	//	min_alarm	not set for b2_capabilityState
	//	max_warning	not set for b2_capabilityState
	//	min_warning	not set for b2_capabilityState
	//	delta_t	not set for b2_capabilityState
	//	delta_val	not set for b2_capabilityState
	b2_capabilitystate_prop.set_event_rel_change("0.1");
	b2_capabilitystate_prop.set_event_abs_change("0.1");
	
	{
		vector<string> labels;
		labels.push_back("UNAVAILABLE");
		labels.push_back("STANDBY");
		labels.push_back("OPERATE");
		labels.push_back("CONFIGURE");
		b2_capabilitystate_prop.set_enum_labels(labels);
	}
	b2_capabilitystate->set_default_properties(b2_capabilitystate_prop);
	//	Not Polled
	b2_capabilitystate->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	b2_capabilitystate->set_change_event(true, false);
	att_list.push_back(b2_capabilitystate);

	//	Attribute : b2_samplingClock
	b2_samplingClockAttrib	*b2_samplingclock = new b2_samplingClockAttrib();
	Tango::UserDefaultAttrProp	b2_samplingclock_prop;
	b2_samplingclock_prop.set_description("Band sampling clock frequency in Hertz");
	//	label	not set for b2_samplingClock
	b2_samplingclock_prop.set_unit("Hz");
	//	standard_unit	not set for b2_samplingClock
	//	display_unit	not set for b2_samplingClock
	//	format	not set for b2_samplingClock
	//	max_value	not set for b2_samplingClock
	//	min_value	not set for b2_samplingClock
	//	max_alarm	not set for b2_samplingClock
	//	min_alarm	not set for b2_samplingClock
	//	max_warning	not set for b2_samplingClock
	//	min_warning	not set for b2_samplingClock
	//	delta_t	not set for b2_samplingClock
	//	delta_val	not set for b2_samplingClock
	b2_samplingclock_prop.set_event_period("3000");
	b2_samplingclock_prop.set_event_rel_change("0.1");
	b2_samplingclock_prop.set_event_abs_change("0.1");
	
	b2_samplingclock->set_default_properties(b2_samplingclock_prop);
	b2_samplingclock->set_polling_period(3000);
	b2_samplingclock->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	b2_samplingclock->set_change_event(true, false);
	att_list.push_back(b2_samplingclock);

	//	Attribute : b2_synchronisedClock
	b2_synchronisedClockAttrib	*b2_synchronisedclock = new b2_synchronisedClockAttrib();
	Tango::UserDefaultAttrProp	b2_synchronisedclock_prop;
	b2_synchronisedclock_prop.set_description("Band clock synchronised to TFR. \nNormally a boolean flag, but CHANGE_EVENT cannot be defined for boolean data types.");
	//	label	not set for b2_synchronisedClock
	//	unit	not set for b2_synchronisedClock
	//	standard_unit	not set for b2_synchronisedClock
	//	display_unit	not set for b2_synchronisedClock
	//	format	not set for b2_synchronisedClock
	//	max_value	not set for b2_synchronisedClock
	//	min_value	not set for b2_synchronisedClock
	//	max_alarm	not set for b2_synchronisedClock
	//	min_alarm	not set for b2_synchronisedClock
	//	max_warning	not set for b2_synchronisedClock
	//	min_warning	not set for b2_synchronisedClock
	//	delta_t	not set for b2_synchronisedClock
	//	delta_val	not set for b2_synchronisedClock
	b2_synchronisedclock_prop.set_event_rel_change("0.1");
	b2_synchronisedclock_prop.set_event_abs_change("0.1");
	
	b2_synchronisedclock->set_default_properties(b2_synchronisedclock_prop);
	b2_synchronisedclock->set_polling_period(3000);
	b2_synchronisedclock->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	b2_synchronisedclock->set_change_event(true, false);
	att_list.push_back(b2_synchronisedclock);

	//	Attribute : b3_capabilityState
	b3_capabilityStateAttrib	*b3_capabilitystate = new b3_capabilityStateAttrib();
	Tango::UserDefaultAttrProp	b3_capabilitystate_prop;
	b3_capabilitystate_prop.set_description("Band capability state");
	//	label	not set for b3_capabilityState
	//	unit	not set for b3_capabilityState
	//	standard_unit	not set for b3_capabilityState
	//	display_unit	not set for b3_capabilityState
	//	format	not set for b3_capabilityState
	//	max_value	not set for b3_capabilityState
	//	min_value	not set for b3_capabilityState
	//	max_alarm	not set for b3_capabilityState
	//	min_alarm	not set for b3_capabilityState
	//	max_warning	not set for b3_capabilityState
	//	min_warning	not set for b3_capabilityState
	//	delta_t	not set for b3_capabilityState
	//	delta_val	not set for b3_capabilityState
	b3_capabilitystate_prop.set_event_rel_change("0.1");
	b3_capabilitystate_prop.set_event_abs_change("0.1");
	
	{
		vector<string> labels;
		labels.push_back("UNAVAILABLE");
		labels.push_back("STANDBY");
		labels.push_back("OPERATE");
		labels.push_back("CONFIGURE");
		b3_capabilitystate_prop.set_enum_labels(labels);
	}
	b3_capabilitystate->set_default_properties(b3_capabilitystate_prop);
	//	Not Polled
	b3_capabilitystate->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	b3_capabilitystate->set_change_event(true, false);
	att_list.push_back(b3_capabilitystate);

	//	Attribute : b3_samplingClock
	b3_samplingClockAttrib	*b3_samplingclock = new b3_samplingClockAttrib();
	Tango::UserDefaultAttrProp	b3_samplingclock_prop;
	b3_samplingclock_prop.set_description("Band sampling clock frequency in Hertz");
	//	label	not set for b3_samplingClock
	//	unit	not set for b3_samplingClock
	//	standard_unit	not set for b3_samplingClock
	//	display_unit	not set for b3_samplingClock
	//	format	not set for b3_samplingClock
	//	max_value	not set for b3_samplingClock
	//	min_value	not set for b3_samplingClock
	//	max_alarm	not set for b3_samplingClock
	//	min_alarm	not set for b3_samplingClock
	//	max_warning	not set for b3_samplingClock
	//	min_warning	not set for b3_samplingClock
	//	delta_t	not set for b3_samplingClock
	//	delta_val	not set for b3_samplingClock
	b3_samplingclock_prop.set_event_period("3000");
	b3_samplingclock_prop.set_event_rel_change("0.1");
	b3_samplingclock_prop.set_event_abs_change("0.1");
	
	b3_samplingclock->set_default_properties(b3_samplingclock_prop);
	b3_samplingclock->set_polling_period(3000);
	b3_samplingclock->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	b3_samplingclock->set_change_event(true, false);
	att_list.push_back(b3_samplingclock);

	//	Attribute : b3_synchronisedClock
	b3_synchronisedClockAttrib	*b3_synchronisedclock = new b3_synchronisedClockAttrib();
	Tango::UserDefaultAttrProp	b3_synchronisedclock_prop;
	b3_synchronisedclock_prop.set_description("Band clock synchronised to TFR.  Normally a boolean flag, but CHANGE_EVENT cannot be defined for boolean data types");
	//	label	not set for b3_synchronisedClock
	//	unit	not set for b3_synchronisedClock
	//	standard_unit	not set for b3_synchronisedClock
	//	display_unit	not set for b3_synchronisedClock
	//	format	not set for b3_synchronisedClock
	//	max_value	not set for b3_synchronisedClock
	//	min_value	not set for b3_synchronisedClock
	//	max_alarm	not set for b3_synchronisedClock
	//	min_alarm	not set for b3_synchronisedClock
	//	max_warning	not set for b3_synchronisedClock
	//	min_warning	not set for b3_synchronisedClock
	//	delta_t	not set for b3_synchronisedClock
	//	delta_val	not set for b3_synchronisedClock
	b3_synchronisedclock_prop.set_event_rel_change("0.1");
	b3_synchronisedclock_prop.set_event_abs_change("0.1");
	
	b3_synchronisedclock->set_default_properties(b3_synchronisedclock_prop);
	b3_synchronisedclock->set_polling_period(3000);
	b3_synchronisedclock->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	b3_synchronisedclock->set_change_event(true, false);
	att_list.push_back(b3_synchronisedclock);

	//	Attribute : b4_capabilityState
	b4_capabilityStateAttrib	*b4_capabilitystate = new b4_capabilityStateAttrib();
	Tango::UserDefaultAttrProp	b4_capabilitystate_prop;
	b4_capabilitystate_prop.set_description("Band capability state");
	//	label	not set for b4_capabilityState
	//	unit	not set for b4_capabilityState
	//	standard_unit	not set for b4_capabilityState
	//	display_unit	not set for b4_capabilityState
	//	format	not set for b4_capabilityState
	//	max_value	not set for b4_capabilityState
	//	min_value	not set for b4_capabilityState
	//	max_alarm	not set for b4_capabilityState
	//	min_alarm	not set for b4_capabilityState
	//	max_warning	not set for b4_capabilityState
	//	min_warning	not set for b4_capabilityState
	//	delta_t	not set for b4_capabilityState
	//	delta_val	not set for b4_capabilityState
	b4_capabilitystate_prop.set_event_rel_change("0.1");
	b4_capabilitystate_prop.set_event_abs_change("0.1");
	
	{
		vector<string> labels;
		labels.push_back("UNAVAILABLE");
		labels.push_back("STANDBY");
		labels.push_back("OPERATE");
		labels.push_back("CONFIGURE");
		b4_capabilitystate_prop.set_enum_labels(labels);
	}
	b4_capabilitystate->set_default_properties(b4_capabilitystate_prop);
	//	Not Polled
	b4_capabilitystate->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	b4_capabilitystate->set_change_event(true, false);
	att_list.push_back(b4_capabilitystate);

	//	Attribute : b4_samplingClock
	b4_samplingClockAttrib	*b4_samplingclock = new b4_samplingClockAttrib();
	Tango::UserDefaultAttrProp	b4_samplingclock_prop;
	b4_samplingclock_prop.set_description("Band sampling clock frequency in Hertz");
	//	label	not set for b4_samplingClock
	b4_samplingclock_prop.set_unit("Hz");
	//	standard_unit	not set for b4_samplingClock
	//	display_unit	not set for b4_samplingClock
	//	format	not set for b4_samplingClock
	//	max_value	not set for b4_samplingClock
	//	min_value	not set for b4_samplingClock
	//	max_alarm	not set for b4_samplingClock
	//	min_alarm	not set for b4_samplingClock
	//	max_warning	not set for b4_samplingClock
	//	min_warning	not set for b4_samplingClock
	//	delta_t	not set for b4_samplingClock
	//	delta_val	not set for b4_samplingClock
	b4_samplingclock_prop.set_event_period("3000");
	b4_samplingclock_prop.set_event_rel_change("0.1");
	b4_samplingclock_prop.set_event_abs_change("0.1");
	
	b4_samplingclock->set_default_properties(b4_samplingclock_prop);
	b4_samplingclock->set_polling_period(3000);
	b4_samplingclock->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	b4_samplingclock->set_change_event(true, false);
	att_list.push_back(b4_samplingclock);

	//	Attribute : b4_synchronisedClock
	b4_synchronisedClockAttrib	*b4_synchronisedclock = new b4_synchronisedClockAttrib();
	Tango::UserDefaultAttrProp	b4_synchronisedclock_prop;
	b4_synchronisedclock_prop.set_description("Band clock synchronised to TFR.  Normally a boolean flag, but CHANGE_EVENT cannot be defined for boolean data types");
	//	label	not set for b4_synchronisedClock
	//	unit	not set for b4_synchronisedClock
	//	standard_unit	not set for b4_synchronisedClock
	//	display_unit	not set for b4_synchronisedClock
	//	format	not set for b4_synchronisedClock
	//	max_value	not set for b4_synchronisedClock
	//	min_value	not set for b4_synchronisedClock
	//	max_alarm	not set for b4_synchronisedClock
	//	min_alarm	not set for b4_synchronisedClock
	//	max_warning	not set for b4_synchronisedClock
	//	min_warning	not set for b4_synchronisedClock
	//	delta_t	not set for b4_synchronisedClock
	//	delta_val	not set for b4_synchronisedClock
	b4_synchronisedclock_prop.set_event_rel_change("0.1");
	b4_synchronisedclock_prop.set_event_abs_change("0.1");
	
	b4_synchronisedclock->set_default_properties(b4_synchronisedclock_prop);
	b4_synchronisedclock->set_polling_period(3000);
	b4_synchronisedclock->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	b4_synchronisedclock->set_change_event(true, false);
	att_list.push_back(b4_synchronisedclock);

	//	Attribute : b5_capabilityState
	b5_capabilityStateAttrib	*b5_capabilitystate = new b5_capabilityStateAttrib();
	Tango::UserDefaultAttrProp	b5_capabilitystate_prop;
	b5_capabilitystate_prop.set_description("Band capability state");
	//	label	not set for b5_capabilityState
	//	unit	not set for b5_capabilityState
	//	standard_unit	not set for b5_capabilityState
	//	display_unit	not set for b5_capabilityState
	//	format	not set for b5_capabilityState
	//	max_value	not set for b5_capabilityState
	//	min_value	not set for b5_capabilityState
	//	max_alarm	not set for b5_capabilityState
	//	min_alarm	not set for b5_capabilityState
	//	max_warning	not set for b5_capabilityState
	//	min_warning	not set for b5_capabilityState
	//	delta_t	not set for b5_capabilityState
	//	delta_val	not set for b5_capabilityState
	b5_capabilitystate_prop.set_event_rel_change("0.1");
	b5_capabilitystate_prop.set_event_abs_change("0.1");
	
	{
		vector<string> labels;
		labels.push_back("UNAVAILABLE");
		labels.push_back("STANDBY");
		labels.push_back("OPERATE");
		labels.push_back("CONFIGURE");
		b5_capabilitystate_prop.set_enum_labels(labels);
	}
	b5_capabilitystate->set_default_properties(b5_capabilitystate_prop);
	//	Not Polled
	b5_capabilitystate->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	b5_capabilitystate->set_change_event(true, false);
	att_list.push_back(b5_capabilitystate);

	//	Attribute : b5_samplingClock
	b5_samplingClockAttrib	*b5_samplingclock = new b5_samplingClockAttrib();
	Tango::UserDefaultAttrProp	b5_samplingclock_prop;
	b5_samplingclock_prop.set_description("Band sampling clock frequency in Hertz");
	//	label	not set for b5_samplingClock
	b5_samplingclock_prop.set_unit("Hz");
	//	standard_unit	not set for b5_samplingClock
	//	display_unit	not set for b5_samplingClock
	//	format	not set for b5_samplingClock
	//	max_value	not set for b5_samplingClock
	//	min_value	not set for b5_samplingClock
	//	max_alarm	not set for b5_samplingClock
	//	min_alarm	not set for b5_samplingClock
	//	max_warning	not set for b5_samplingClock
	//	min_warning	not set for b5_samplingClock
	//	delta_t	not set for b5_samplingClock
	//	delta_val	not set for b5_samplingClock
	b5_samplingclock_prop.set_event_period("3000");
	b5_samplingclock_prop.set_event_rel_change("0.1");
	b5_samplingclock_prop.set_event_abs_change("0.1");
	
	b5_samplingclock->set_default_properties(b5_samplingclock_prop);
	b5_samplingclock->set_polling_period(3000);
	b5_samplingclock->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	b5_samplingclock->set_change_event(true, false);
	att_list.push_back(b5_samplingclock);

	//	Attribute : b5_synchronisedClock
	b5_synchronisedClockAttrib	*b5_synchronisedclock = new b5_synchronisedClockAttrib();
	Tango::UserDefaultAttrProp	b5_synchronisedclock_prop;
	b5_synchronisedclock_prop.set_description("Band clock synchronised to TFR.  Normally a boolean flag, but CHANGE_EVENT cannot be defined for boolean data types");
	//	label	not set for b5_synchronisedClock
	//	unit	not set for b5_synchronisedClock
	//	standard_unit	not set for b5_synchronisedClock
	//	display_unit	not set for b5_synchronisedClock
	//	format	not set for b5_synchronisedClock
	//	max_value	not set for b5_synchronisedClock
	//	min_value	not set for b5_synchronisedClock
	//	max_alarm	not set for b5_synchronisedClock
	//	min_alarm	not set for b5_synchronisedClock
	//	max_warning	not set for b5_synchronisedClock
	//	min_warning	not set for b5_synchronisedClock
	//	delta_t	not set for b5_synchronisedClock
	//	delta_val	not set for b5_synchronisedClock
	b5_synchronisedclock_prop.set_event_rel_change("0.1");
	b5_synchronisedclock_prop.set_event_abs_change("0.1");
	
	b5_synchronisedclock->set_default_properties(b5_synchronisedclock_prop);
	b5_synchronisedclock->set_polling_period(3000);
	b5_synchronisedclock->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	b5_synchronisedclock->set_change_event(true, false);
	att_list.push_back(b5_synchronisedclock);

	//	Attribute : noisesource_offTime
	noisesource_offTimeAttrib	*noisesource_offtime = new noisesource_offTimeAttrib();
	Tango::UserDefaultAttrProp	noisesource_offtime_prop;
	noisesource_offtime_prop.set_description("Overall device noise source off time");
	//	label	not set for noisesource_offTime
	//	unit	not set for noisesource_offTime
	//	standard_unit	not set for noisesource_offTime
	//	display_unit	not set for noisesource_offTime
	//	format	not set for noisesource_offTime
	//	max_value	not set for noisesource_offTime
	//	min_value	not set for noisesource_offTime
	//	max_alarm	not set for noisesource_offTime
	//	min_alarm	not set for noisesource_offTime
	//	max_warning	not set for noisesource_offTime
	//	min_warning	not set for noisesource_offTime
	//	delta_t	not set for noisesource_offTime
	//	delta_val	not set for noisesource_offTime
	
	noisesource_offtime->set_default_properties(noisesource_offtime_prop);
	//	Not Polled
	noisesource_offtime->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(noisesource_offtime);

	//	Attribute : noisesource_onTime
	noisesource_onTimeAttrib	*noisesource_ontime = new noisesource_onTimeAttrib();
	Tango::UserDefaultAttrProp	noisesource_ontime_prop;
	noisesource_ontime_prop.set_description("Overall device noise source offtime");
	//	label	not set for noisesource_onTime
	//	unit	not set for noisesource_onTime
	//	standard_unit	not set for noisesource_onTime
	//	display_unit	not set for noisesource_onTime
	//	format	not set for noisesource_onTime
	//	max_value	not set for noisesource_onTime
	//	min_value	not set for noisesource_onTime
	//	max_alarm	not set for noisesource_onTime
	//	min_alarm	not set for noisesource_onTime
	//	max_warning	not set for noisesource_onTime
	//	min_warning	not set for noisesource_onTime
	//	delta_t	not set for noisesource_onTime
	//	delta_val	not set for noisesource_onTime
	
	noisesource_ontime->set_default_properties(noisesource_ontime_prop);
	//	Not Polled
	noisesource_ontime->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(noisesource_ontime);

	//	Attribute : noisesource_period
	noisesource_periodAttrib	*noisesource_period = new noisesource_periodAttrib();
	Tango::UserDefaultAttrProp	noisesource_period_prop;
	noisesource_period_prop.set_description("Overall device noise source period.");
	//	label	not set for noisesource_period
	//	unit	not set for noisesource_period
	//	standard_unit	not set for noisesource_period
	//	display_unit	not set for noisesource_period
	//	format	not set for noisesource_period
	//	max_value	not set for noisesource_period
	//	min_value	not set for noisesource_period
	//	max_alarm	not set for noisesource_period
	//	min_alarm	not set for noisesource_period
	//	max_warning	not set for noisesource_period
	//	min_warning	not set for noisesource_period
	//	delta_t	not set for noisesource_period
	//	delta_val	not set for noisesource_period
	
	noisesource_period->set_default_properties(noisesource_period_prop);
	//	Not Polled
	noisesource_period->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(noisesource_period);

	//	Attribute : noisesource_startTime
	noisesource_startTimeAttrib	*noisesource_starttime = new noisesource_startTimeAttrib();
	Tango::UserDefaultAttrProp	noisesource_starttime_prop;
	noisesource_starttime_prop.set_description("Overall device noise source start time.");
	//	label	not set for noisesource_startTime
	//	unit	not set for noisesource_startTime
	//	standard_unit	not set for noisesource_startTime
	//	display_unit	not set for noisesource_startTime
	//	format	not set for noisesource_startTime
	//	max_value	not set for noisesource_startTime
	//	min_value	not set for noisesource_startTime
	//	max_alarm	not set for noisesource_startTime
	//	min_alarm	not set for noisesource_startTime
	//	max_warning	not set for noisesource_startTime
	//	min_warning	not set for noisesource_startTime
	//	delta_t	not set for noisesource_startTime
	//	delta_val	not set for noisesource_startTime
	
	noisesource_starttime->set_default_properties(noisesource_starttime_prop);
	//	Not Polled
	noisesource_starttime->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(noisesource_starttime);

	//	Attribute : rx_fwVersions
	rx_fwVersionsAttrib	*rx_fwversions = new rx_fwVersionsAttrib();
	Tango::UserDefaultAttrProp	rx_fwversions_prop;
	rx_fwversions_prop.set_description("Firmware serial numbers");
	//	label	not set for rx_fwVersions
	//	unit	not set for rx_fwVersions
	//	standard_unit	not set for rx_fwVersions
	//	display_unit	not set for rx_fwVersions
	//	format	not set for rx_fwVersions
	//	max_value	not set for rx_fwVersions
	//	min_value	not set for rx_fwVersions
	//	max_alarm	not set for rx_fwVersions
	//	min_alarm	not set for rx_fwVersions
	//	max_warning	not set for rx_fwVersions
	//	min_warning	not set for rx_fwVersions
	//	delta_t	not set for rx_fwVersions
	//	delta_val	not set for rx_fwVersions
	
	rx_fwversions->set_default_properties(rx_fwversions_prop);
	//	Not Polled
	rx_fwversions->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(rx_fwversions);

	//	Attribute : rx_healthState
	rx_healthStateAttrib	*rx_healthstate = new rx_healthStateAttrib();
	Tango::UserDefaultAttrProp	rx_healthstate_prop;
	rx_healthstate_prop.set_description("Aggregated sub-element health\nNormal = all MCs healthy. Degraded = at least one RX Sampler and RXPU healthy.\nFailed = no sampler is healthy or RXPU is not healthy.");
	//	label	not set for rx_healthState
	//	unit	not set for rx_healthState
	//	standard_unit	not set for rx_healthState
	//	display_unit	not set for rx_healthState
	//	format	not set for rx_healthState
	//	max_value	not set for rx_healthState
	//	min_value	not set for rx_healthState
	//	max_alarm	not set for rx_healthState
	//	min_alarm	not set for rx_healthState
	//	max_warning	not set for rx_healthState
	//	min_warning	not set for rx_healthState
	//	delta_t	not set for rx_healthState
	//	delta_val	not set for rx_healthState
	rx_healthstate_prop.set_event_rel_change("0.1");
	rx_healthstate_prop.set_event_abs_change("0.1");
	
	{
		vector<string> labels;
		labels.push_back("NORMAL");
		labels.push_back("DEGRADED");
		labels.push_back("FAILED");
		rx_healthstate_prop.set_enum_labels(labels);
	}
	rx_healthstate->set_default_properties(rx_healthstate_prop);
	//	Not Polled
	rx_healthstate->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rx_healthstate->set_change_event(true, false);
	att_list.push_back(rx_healthstate);

	//	Attribute : rx_mode
	rx_modeAttrib	*rx_mode = new rx_modeAttrib();
	Tango::UserDefaultAttrProp	rx_mode_prop;
	//	description	not set for rx_mode
	//	label	not set for rx_mode
	//	unit	not set for rx_mode
	//	standard_unit	not set for rx_mode
	//	display_unit	not set for rx_mode
	//	format	not set for rx_mode
	//	max_value	not set for rx_mode
	//	min_value	not set for rx_mode
	//	max_alarm	not set for rx_mode
	//	min_alarm	not set for rx_mode
	//	max_warning	not set for rx_mode
	//	min_warning	not set for rx_mode
	//	delta_t	not set for rx_mode
	//	delta_val	not set for rx_mode
	rx_mode_prop.set_event_rel_change("0.1");
	rx_mode_prop.set_event_abs_change("0.1");
	
	{
		vector<string> labels;
		labels.push_back("DATA-CAPTURE");
		labels.push_back("STANDBY-FP");
		labels.push_back("STANDBY-LP");
		labels.push_back("MAINTENANCE");
		labels.push_back("STARTUP");
		labels.push_back("CONFIGURE");
		rx_mode_prop.set_enum_labels(labels);
	}
	rx_mode->set_default_properties(rx_mode_prop);
	//	Not Polled
	rx_mode->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rx_mode->set_change_event(true, false);
	att_list.push_back(rx_mode);

	//	Attribute : rx_powerState
	rx_powerStateAttrib	*rx_powerstate = new rx_powerStateAttrib();
	Tango::UserDefaultAttrProp	rx_powerstate_prop;
	rx_powerstate_prop.set_description("Current power state");
	//	label	not set for rx_powerState
	//	unit	not set for rx_powerState
	//	standard_unit	not set for rx_powerState
	//	display_unit	not set for rx_powerState
	//	format	not set for rx_powerState
	//	max_value	not set for rx_powerState
	//	min_value	not set for rx_powerState
	//	max_alarm	not set for rx_powerState
	//	min_alarm	not set for rx_powerState
	//	max_warning	not set for rx_powerState
	//	min_warning	not set for rx_powerState
	//	delta_t	not set for rx_powerState
	//	delta_val	not set for rx_powerState
	rx_powerstate_prop.set_event_rel_change("0.1");
	rx_powerstate_prop.set_event_abs_change("0.1");
	
	{
		vector<string> labels;
		labels.push_back("FULL-POWER");
		labels.push_back("LOW-POWER");
		rx_powerstate_prop.set_enum_labels(labels);
	}
	rx_powerstate->set_default_properties(rx_powerstate_prop);
	//	Not Polled
	rx_powerstate->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rx_powerstate->set_change_event(true, false);
	att_list.push_back(rx_powerstate);

	//	Attribute : rx_protocolVersion
	rx_protocolVersionAttrib	*rx_protocolversion = new rx_protocolVersionAttrib();
	Tango::UserDefaultAttrProp	rx_protocolversion_prop;
	rx_protocolversion_prop.set_description("Device server protocol version");
	//	label	not set for rx_protocolVersion
	//	unit	not set for rx_protocolVersion
	//	standard_unit	not set for rx_protocolVersion
	//	display_unit	not set for rx_protocolVersion
	//	format	not set for rx_protocolVersion
	//	max_value	not set for rx_protocolVersion
	//	min_value	not set for rx_protocolVersion
	//	max_alarm	not set for rx_protocolVersion
	//	min_alarm	not set for rx_protocolVersion
	//	max_warning	not set for rx_protocolVersion
	//	min_warning	not set for rx_protocolVersion
	//	delta_t	not set for rx_protocolVersion
	//	delta_val	not set for rx_protocolVersion
	
	rx_protocolversion->set_default_properties(rx_protocolversion_prop);
	//	Not Polled
	rx_protocolversion->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(rx_protocolversion);

	//	Attribute : rx_serialNumbers
	rx_serialNumbersAttrib	*rx_serialnumbers = new rx_serialNumbersAttrib();
	Tango::UserDefaultAttrProp	rx_serialnumbers_prop;
	rx_serialnumbers_prop.set_description("Device Serial number");
	//	label	not set for rx_serialNumbers
	//	unit	not set for rx_serialNumbers
	//	standard_unit	not set for rx_serialNumbers
	//	display_unit	not set for rx_serialNumbers
	//	format	not set for rx_serialNumbers
	//	max_value	not set for rx_serialNumbers
	//	min_value	not set for rx_serialNumbers
	//	max_alarm	not set for rx_serialNumbers
	//	min_alarm	not set for rx_serialNumbers
	//	max_warning	not set for rx_serialNumbers
	//	min_warning	not set for rx_serialNumbers
	//	delta_t	not set for rx_serialNumbers
	//	delta_val	not set for rx_serialNumbers
	
	rx_serialnumbers->set_default_properties(rx_serialnumbers_prop);
	//	Not Polled
	rx_serialnumbers->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(rx_serialnumbers);

	//	Attribute : rx_swVersions
	rx_swVersionsAttrib	*rx_swversions = new rx_swVersionsAttrib();
	Tango::UserDefaultAttrProp	rx_swversions_prop;
	rx_swversions_prop.set_description("Software serial numbers");
	//	label	not set for rx_swVersions
	//	unit	not set for rx_swVersions
	//	standard_unit	not set for rx_swVersions
	//	display_unit	not set for rx_swVersions
	//	format	not set for rx_swVersions
	//	max_value	not set for rx_swVersions
	//	min_value	not set for rx_swVersions
	//	max_alarm	not set for rx_swVersions
	//	min_alarm	not set for rx_swVersions
	//	max_warning	not set for rx_swVersions
	//	min_warning	not set for rx_swVersions
	//	delta_t	not set for rx_swVersions
	//	delta_val	not set for rx_swVersions
	
	rx_swversions->set_default_properties(rx_swversions_prop);
	//	Not Polled
	rx_swversions->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(rx_swversions);

	//	Attribute : rxpu_expectedOnline
	rxpu_expectedOnlineAttrib	*rxpu_expectedonline = new rxpu_expectedOnlineAttrib();
	Tango::UserDefaultAttrProp	rxpu_expectedonline_prop;
	rxpu_expectedonline_prop.set_description("Indicates whether major component is expected online.  mcHealthStatus \nwill be normal if this value is set to false and the device is not installed or offline.");
	//	label	not set for rxpu_expectedOnline
	//	unit	not set for rxpu_expectedOnline
	//	standard_unit	not set for rxpu_expectedOnline
	//	display_unit	not set for rxpu_expectedOnline
	//	format	not set for rxpu_expectedOnline
	//	max_value	not set for rxpu_expectedOnline
	//	min_value	not set for rxpu_expectedOnline
	//	max_alarm	not set for rxpu_expectedOnline
	//	min_alarm	not set for rxpu_expectedOnline
	//	max_warning	not set for rxpu_expectedOnline
	//	min_warning	not set for rxpu_expectedOnline
	//	delta_t	not set for rxpu_expectedOnline
	//	delta_val	not set for rxpu_expectedOnline
	rxpu_expectedonline_prop.set_event_rel_change("0.1");
	rxpu_expectedonline_prop.set_event_abs_change("0.1");
	
	rxpu_expectedonline->set_default_properties(rxpu_expectedonline_prop);
	//	Not Polled
	rxpu_expectedonline->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxpu_expectedonline->set_change_event(true, false);
	att_list.push_back(rxpu_expectedonline);

	//	Attribute : rxpu_healthState
	rxpu_healthStateAttrib	*rxpu_healthstate = new rxpu_healthStateAttrib();
	Tango::UserDefaultAttrProp	rxpu_healthstate_prop;
	rxpu_healthstate_prop.set_description("Major component health status");
	//	label	not set for rxpu_healthState
	//	unit	not set for rxpu_healthState
	//	standard_unit	not set for rxpu_healthState
	//	display_unit	not set for rxpu_healthState
	//	format	not set for rxpu_healthState
	//	max_value	not set for rxpu_healthState
	//	min_value	not set for rxpu_healthState
	//	max_alarm	not set for rxpu_healthState
	//	min_alarm	not set for rxpu_healthState
	//	max_warning	not set for rxpu_healthState
	//	min_warning	not set for rxpu_healthState
	//	delta_t	not set for rxpu_healthState
	//	delta_val	not set for rxpu_healthState
	rxpu_healthstate_prop.set_event_rel_change("0.1");
	rxpu_healthstate_prop.set_event_abs_change("0.1");
	
	{
		vector<string> labels;
		labels.push_back("NORMAL");
		labels.push_back("DEGRADED");
		labels.push_back("FAILED");
		rxpu_healthstate_prop.set_enum_labels(labels);
	}
	rxpu_healthstate->set_default_properties(rxpu_healthstate_prop);
	//	Not Polled
	rxpu_healthstate->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(rxpu_healthstate);

	//	Attribute : rxpu_hourCounter
	rxpu_hourCounterAttrib	*rxpu_hourcounter = new rxpu_hourCounterAttrib();
	Tango::UserDefaultAttrProp	rxpu_hourcounter_prop;
	rxpu_hourcounter_prop.set_description("Major component total operational time");
	//	label	not set for rxpu_hourCounter
	//	unit	not set for rxpu_hourCounter
	//	standard_unit	not set for rxpu_hourCounter
	//	display_unit	not set for rxpu_hourCounter
	//	format	not set for rxpu_hourCounter
	//	max_value	not set for rxpu_hourCounter
	//	min_value	not set for rxpu_hourCounter
	//	max_alarm	not set for rxpu_hourCounter
	//	min_alarm	not set for rxpu_hourCounter
	//	max_warning	not set for rxpu_hourCounter
	//	min_warning	not set for rxpu_hourCounter
	//	delta_t	not set for rxpu_hourCounter
	//	delta_val	not set for rxpu_hourCounter
	
	rxpu_hourcounter->set_default_properties(rxpu_hourcounter_prop);
	//	Not Polled
	rxpu_hourcounter->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(rxpu_hourcounter);

	//	Attribute : rxpu_operationalTime
	rxpu_operationalTimeAttrib	*rxpu_operationaltime = new rxpu_operationalTimeAttrib();
	Tango::UserDefaultAttrProp	rxpu_operationaltime_prop;
	rxpu_operationaltime_prop.set_description("Controller total operational time");
	//	label	not set for rxpu_operationalTime
	rxpu_operationaltime_prop.set_unit("s");
	//	standard_unit	not set for rxpu_operationalTime
	//	display_unit	not set for rxpu_operationalTime
	//	format	not set for rxpu_operationalTime
	//	max_value	not set for rxpu_operationalTime
	//	min_value	not set for rxpu_operationalTime
	//	max_alarm	not set for rxpu_operationalTime
	//	min_alarm	not set for rxpu_operationalTime
	//	max_warning	not set for rxpu_operationalTime
	//	min_warning	not set for rxpu_operationalTime
	//	delta_t	not set for rxpu_operationalTime
	//	delta_val	not set for rxpu_operationalTime
	
	rxpu_operationaltime->set_default_properties(rxpu_operationaltime_prop);
	//	Not Polled
	rxpu_operationaltime->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(rxpu_operationaltime);

	//	Attribute : rxpu_supplyCurrent
	rxpu_supplyCurrentAttrib	*rxpu_supplycurrent = new rxpu_supplyCurrentAttrib();
	Tango::UserDefaultAttrProp	rxpu_supplycurrent_prop;
	rxpu_supplycurrent_prop.set_description("Controller device supply current");
	//	label	not set for rxpu_supplyCurrent
	//	unit	not set for rxpu_supplyCurrent
	//	standard_unit	not set for rxpu_supplyCurrent
	//	display_unit	not set for rxpu_supplyCurrent
	//	format	not set for rxpu_supplyCurrent
	//	max_value	not set for rxpu_supplyCurrent
	//	min_value	not set for rxpu_supplyCurrent
	//	max_alarm	not set for rxpu_supplyCurrent
	//	min_alarm	not set for rxpu_supplyCurrent
	//	max_warning	not set for rxpu_supplyCurrent
	//	min_warning	not set for rxpu_supplyCurrent
	//	delta_t	not set for rxpu_supplyCurrent
	//	delta_val	not set for rxpu_supplyCurrent
	rxpu_supplycurrent_prop.set_event_period("3000");
	
	rxpu_supplycurrent->set_default_properties(rxpu_supplycurrent_prop);
	rxpu_supplycurrent->set_polling_period(3000);
	rxpu_supplycurrent->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxpu_supplycurrent->set_change_event(true, false);
	att_list.push_back(rxpu_supplycurrent);

	//	Attribute : rxpu_supplyVoltage
	rxpu_supplyVoltageAttrib	*rxpu_supplyvoltage = new rxpu_supplyVoltageAttrib();
	Tango::UserDefaultAttrProp	rxpu_supplyvoltage_prop;
	rxpu_supplyvoltage_prop.set_description("Controller device supply voltage");
	//	label	not set for rxpu_supplyVoltage
	//	unit	not set for rxpu_supplyVoltage
	//	standard_unit	not set for rxpu_supplyVoltage
	//	display_unit	not set for rxpu_supplyVoltage
	//	format	not set for rxpu_supplyVoltage
	//	max_value	not set for rxpu_supplyVoltage
	//	min_value	not set for rxpu_supplyVoltage
	//	max_alarm	not set for rxpu_supplyVoltage
	//	min_alarm	not set for rxpu_supplyVoltage
	//	max_warning	not set for rxpu_supplyVoltage
	//	min_warning	not set for rxpu_supplyVoltage
	//	delta_t	not set for rxpu_supplyVoltage
	//	delta_val	not set for rxpu_supplyVoltage
	rxpu_supplyvoltage_prop.set_event_period("3000");
	
	rxpu_supplyvoltage->set_default_properties(rxpu_supplyvoltage_prop);
	rxpu_supplyvoltage->set_polling_period(3000);
	rxpu_supplyvoltage->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxpu_supplyvoltage->set_change_event(true, false);
	att_list.push_back(rxpu_supplyvoltage);

	//	Attribute : rxpu_temperature
	rxpu_temperatureAttrib	*rxpu_temperature = new rxpu_temperatureAttrib();
	Tango::UserDefaultAttrProp	rxpu_temperature_prop;
	rxpu_temperature_prop.set_description("Controller device temperature");
	//	label	not set for rxpu_temperature
	rxpu_temperature_prop.set_unit("°C");
	//	standard_unit	not set for rxpu_temperature
	//	display_unit	not set for rxpu_temperature
	//	format	not set for rxpu_temperature
	//	max_value	not set for rxpu_temperature
	//	min_value	not set for rxpu_temperature
	//	max_alarm	not set for rxpu_temperature
	//	min_alarm	not set for rxpu_temperature
	//	max_warning	not set for rxpu_temperature
	//	min_warning	not set for rxpu_temperature
	//	delta_t	not set for rxpu_temperature
	//	delta_val	not set for rxpu_temperature
	rxpu_temperature_prop.set_event_period("3000");
	
	rxpu_temperature->set_default_properties(rxpu_temperature_prop);
	rxpu_temperature->set_polling_period(3000);
	rxpu_temperature->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(rxpu_temperature);

	//	Attribute : rxs123_adcPower
	rxs123_adcPowerAttrib	*rxs123_adcpower = new rxs123_adcPowerAttrib();
	Tango::UserDefaultAttrProp	rxs123_adcpower_prop;
	rxs123_adcpower_prop.set_description("Averaged power in dBm");
	//	label	not set for rxs123_adcPower
	rxs123_adcpower_prop.set_unit("dBm");
	//	standard_unit	not set for rxs123_adcPower
	//	display_unit	not set for rxs123_adcPower
	//	format	not set for rxs123_adcPower
	//	max_value	not set for rxs123_adcPower
	//	min_value	not set for rxs123_adcPower
	//	max_alarm	not set for rxs123_adcPower
	//	min_alarm	not set for rxs123_adcPower
	//	max_warning	not set for rxs123_adcPower
	//	min_warning	not set for rxs123_adcPower
	//	delta_t	not set for rxs123_adcPower
	//	delta_val	not set for rxs123_adcPower
	rxs123_adcpower_prop.set_event_period("3000");
	
	rxs123_adcpower->set_default_properties(rxs123_adcpower_prop);
	rxs123_adcpower->set_polling_period(3000);
	rxs123_adcpower->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxs123_adcpower->set_change_event(true, false);
	att_list.push_back(rxs123_adcpower);

	//	Attribute : rxs123_adcVariance
	rxs123_adcVarianceAttrib	*rxs123_adcvariance = new rxs123_adcVarianceAttrib();
	Tango::UserDefaultAttrProp	rxs123_adcvariance_prop;
	rxs123_adcvariance_prop.set_description("Sample variance");
	//	label	not set for rxs123_adcVariance
	rxs123_adcvariance_prop.set_unit("dBm");
	//	standard_unit	not set for rxs123_adcVariance
	//	display_unit	not set for rxs123_adcVariance
	//	format	not set for rxs123_adcVariance
	//	max_value	not set for rxs123_adcVariance
	//	min_value	not set for rxs123_adcVariance
	//	max_alarm	not set for rxs123_adcVariance
	//	min_alarm	not set for rxs123_adcVariance
	//	max_warning	not set for rxs123_adcVariance
	//	min_warning	not set for rxs123_adcVariance
	//	delta_t	not set for rxs123_adcVariance
	//	delta_val	not set for rxs123_adcVariance
	rxs123_adcvariance_prop.set_event_period("3000");
	
	rxs123_adcvariance->set_default_properties(rxs123_adcvariance_prop);
	rxs123_adcvariance->set_polling_period(3000);
	rxs123_adcvariance->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxs123_adcvariance->set_change_event(true, false);
	att_list.push_back(rxs123_adcvariance);

	//	Attribute : rxs123_expectedOnline
	rxs123_expectedOnlineAttrib	*rxs123_expectedonline = new rxs123_expectedOnlineAttrib();
	Tango::UserDefaultAttrProp	rxs123_expectedonline_prop;
	rxs123_expectedonline_prop.set_description("Indicates whether major component is expected online.  mcHealthStatus \nwill be normal if this value is set to false and the device is not installed or offline.");
	//	label	not set for rxs123_expectedOnline
	//	unit	not set for rxs123_expectedOnline
	//	standard_unit	not set for rxs123_expectedOnline
	//	display_unit	not set for rxs123_expectedOnline
	//	format	not set for rxs123_expectedOnline
	//	max_value	not set for rxs123_expectedOnline
	//	min_value	not set for rxs123_expectedOnline
	//	max_alarm	not set for rxs123_expectedOnline
	//	min_alarm	not set for rxs123_expectedOnline
	//	max_warning	not set for rxs123_expectedOnline
	//	min_warning	not set for rxs123_expectedOnline
	//	delta_t	not set for rxs123_expectedOnline
	//	delta_val	not set for rxs123_expectedOnline
	rxs123_expectedonline_prop.set_event_rel_change("0.1");
	rxs123_expectedonline_prop.set_event_abs_change("0.1");
	
	rxs123_expectedonline->set_default_properties(rxs123_expectedonline_prop);
	//	Not Polled
	rxs123_expectedonline->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxs123_expectedonline->set_change_event(true, false);
	att_list.push_back(rxs123_expectedonline);

	//	Attribute : rxs123_healthState
	rxs123_healthStateAttrib	*rxs123_healthstate = new rxs123_healthStateAttrib();
	Tango::UserDefaultAttrProp	rxs123_healthstate_prop;
	rxs123_healthstate_prop.set_description("Major component health status");
	//	label	not set for rxs123_healthState
	//	unit	not set for rxs123_healthState
	//	standard_unit	not set for rxs123_healthState
	//	display_unit	not set for rxs123_healthState
	//	format	not set for rxs123_healthState
	//	max_value	not set for rxs123_healthState
	//	min_value	not set for rxs123_healthState
	//	max_alarm	not set for rxs123_healthState
	//	min_alarm	not set for rxs123_healthState
	//	max_warning	not set for rxs123_healthState
	//	min_warning	not set for rxs123_healthState
	//	delta_t	not set for rxs123_healthState
	//	delta_val	not set for rxs123_healthState
	rxs123_healthstate_prop.set_event_rel_change("0.1");
	rxs123_healthstate_prop.set_event_abs_change("0.1");
	
	{
		vector<string> labels;
		labels.push_back("NORMAL");
		labels.push_back("DEGRADED");
		labels.push_back("FAILED");
		rxs123_healthstate_prop.set_enum_labels(labels);
	}
	rxs123_healthstate->set_default_properties(rxs123_healthstate_prop);
	//	Not Polled
	rxs123_healthstate->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxs123_healthstate->set_change_event(true, false);
	att_list.push_back(rxs123_healthstate);

	//	Attribute : rxs123_hourCounter
	rxs123_hourCounterAttrib	*rxs123_hourcounter = new rxs123_hourCounterAttrib();
	Tango::UserDefaultAttrProp	rxs123_hourcounter_prop;
	rxs123_hourcounter_prop.set_description("Operational run time in hours");
	//	label	not set for rxs123_hourCounter
	rxs123_hourcounter_prop.set_unit("h");
	//	standard_unit	not set for rxs123_hourCounter
	//	display_unit	not set for rxs123_hourCounter
	//	format	not set for rxs123_hourCounter
	//	max_value	not set for rxs123_hourCounter
	//	min_value	not set for rxs123_hourCounter
	//	max_alarm	not set for rxs123_hourCounter
	//	min_alarm	not set for rxs123_hourCounter
	//	max_warning	not set for rxs123_hourCounter
	//	min_warning	not set for rxs123_hourCounter
	//	delta_t	not set for rxs123_hourCounter
	//	delta_val	not set for rxs123_hourCounter
	
	rxs123_hourcounter->set_default_properties(rxs123_hourcounter_prop);
	//	Not Polled
	rxs123_hourcounter->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(rxs123_hourcounter);

	//	Attribute : rxs123_operationalTime
	rxs123_operationalTimeAttrib	*rxs123_operationaltime = new rxs123_operationalTimeAttrib();
	Tango::UserDefaultAttrProp	rxs123_operationaltime_prop;
	rxs123_operationaltime_prop.set_description("Major component total operational time");
	//	label	not set for rxs123_operationalTime
	rxs123_operationaltime_prop.set_unit("s");
	//	standard_unit	not set for rxs123_operationalTime
	//	display_unit	not set for rxs123_operationalTime
	//	format	not set for rxs123_operationalTime
	//	max_value	not set for rxs123_operationalTime
	//	min_value	not set for rxs123_operationalTime
	//	max_alarm	not set for rxs123_operationalTime
	//	min_alarm	not set for rxs123_operationalTime
	//	max_warning	not set for rxs123_operationalTime
	//	min_warning	not set for rxs123_operationalTime
	//	delta_t	not set for rxs123_operationalTime
	//	delta_val	not set for rxs123_operationalTime
	
	rxs123_operationaltime->set_default_properties(rxs123_operationaltime_prop);
	//	Not Polled
	rxs123_operationaltime->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(rxs123_operationaltime);

	//	Attribute : rxs123_supplyCurrent
	rxs123_supplyCurrentAttrib	*rxs123_supplycurrent = new rxs123_supplyCurrentAttrib();
	Tango::UserDefaultAttrProp	rxs123_supplycurrent_prop;
	rxs123_supplycurrent_prop.set_description("Major component supply current");
	//	label	not set for rxs123_supplyCurrent
	rxs123_supplycurrent_prop.set_unit("mA");
	//	standard_unit	not set for rxs123_supplyCurrent
	//	display_unit	not set for rxs123_supplyCurrent
	//	format	not set for rxs123_supplyCurrent
	//	max_value	not set for rxs123_supplyCurrent
	//	min_value	not set for rxs123_supplyCurrent
	//	max_alarm	not set for rxs123_supplyCurrent
	//	min_alarm	not set for rxs123_supplyCurrent
	//	max_warning	not set for rxs123_supplyCurrent
	//	min_warning	not set for rxs123_supplyCurrent
	//	delta_t	not set for rxs123_supplyCurrent
	//	delta_val	not set for rxs123_supplyCurrent
	rxs123_supplycurrent_prop.set_event_period("3000");
	
	rxs123_supplycurrent->set_default_properties(rxs123_supplycurrent_prop);
	rxs123_supplycurrent->set_polling_period(3000);
	rxs123_supplycurrent->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxs123_supplycurrent->set_change_event(true, false);
	att_list.push_back(rxs123_supplycurrent);

	//	Attribute : rxs123_supplyVoltage
	rxs123_supplyVoltageAttrib	*rxs123_supplyvoltage = new rxs123_supplyVoltageAttrib();
	Tango::UserDefaultAttrProp	rxs123_supplyvoltage_prop;
	rxs123_supplyvoltage_prop.set_description("Major component supply voltage");
	//	label	not set for rxs123_supplyVoltage
	rxs123_supplyvoltage_prop.set_unit("V");
	//	standard_unit	not set for rxs123_supplyVoltage
	//	display_unit	not set for rxs123_supplyVoltage
	//	format	not set for rxs123_supplyVoltage
	//	max_value	not set for rxs123_supplyVoltage
	//	min_value	not set for rxs123_supplyVoltage
	//	max_alarm	not set for rxs123_supplyVoltage
	//	min_alarm	not set for rxs123_supplyVoltage
	//	max_warning	not set for rxs123_supplyVoltage
	//	min_warning	not set for rxs123_supplyVoltage
	//	delta_t	not set for rxs123_supplyVoltage
	//	delta_val	not set for rxs123_supplyVoltage
	rxs123_supplyvoltage_prop.set_event_period("3000");
	
	rxs123_supplyvoltage->set_default_properties(rxs123_supplyvoltage_prop);
	rxs123_supplyvoltage->set_polling_period(3000);
	rxs123_supplyvoltage->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxs123_supplyvoltage->set_change_event(true, false);
	att_list.push_back(rxs123_supplyvoltage);

	//	Attribute : rxs123_temperature
	rxs123_temperatureAttrib	*rxs123_temperature = new rxs123_temperatureAttrib();
	Tango::UserDefaultAttrProp	rxs123_temperature_prop;
	rxs123_temperature_prop.set_description("Major component temperature");
	//	label	not set for rxs123_temperature
	rxs123_temperature_prop.set_unit("°C");
	//	standard_unit	not set for rxs123_temperature
	//	display_unit	not set for rxs123_temperature
	//	format	not set for rxs123_temperature
	//	max_value	not set for rxs123_temperature
	//	min_value	not set for rxs123_temperature
	//	max_alarm	not set for rxs123_temperature
	//	min_alarm	not set for rxs123_temperature
	//	max_warning	not set for rxs123_temperature
	//	min_warning	not set for rxs123_temperature
	//	delta_t	not set for rxs123_temperature
	//	delta_val	not set for rxs123_temperature
	rxs123_temperature_prop.set_event_period("3000");
	
	rxs123_temperature->set_default_properties(rxs123_temperature_prop);
	rxs123_temperature->set_polling_period(3000);
	rxs123_temperature->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxs123_temperature->set_change_event(true, false);
	att_list.push_back(rxs123_temperature);

	//	Attribute : rxs45_adcPower
	rxs45_adcPowerAttrib	*rxs45_adcpower = new rxs45_adcPowerAttrib();
	Tango::UserDefaultAttrProp	rxs45_adcpower_prop;
	rxs45_adcpower_prop.set_description("Averaged power in dBm");
	//	label	not set for rxs45_adcPower
	rxs45_adcpower_prop.set_unit("dBm");
	//	standard_unit	not set for rxs45_adcPower
	//	display_unit	not set for rxs45_adcPower
	//	format	not set for rxs45_adcPower
	//	max_value	not set for rxs45_adcPower
	//	min_value	not set for rxs45_adcPower
	//	max_alarm	not set for rxs45_adcPower
	//	min_alarm	not set for rxs45_adcPower
	//	max_warning	not set for rxs45_adcPower
	//	min_warning	not set for rxs45_adcPower
	//	delta_t	not set for rxs45_adcPower
	//	delta_val	not set for rxs45_adcPower
	rxs45_adcpower_prop.set_event_period("3000");
	
	rxs45_adcpower->set_default_properties(rxs45_adcpower_prop);
	rxs45_adcpower->set_polling_period(3000);
	rxs45_adcpower->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxs45_adcpower->set_change_event(true, false);
	att_list.push_back(rxs45_adcpower);

	//	Attribute : rxs45_adcVariance
	rxs45_adcVarianceAttrib	*rxs45_adcvariance = new rxs45_adcVarianceAttrib();
	Tango::UserDefaultAttrProp	rxs45_adcvariance_prop;
	rxs45_adcvariance_prop.set_description("Sample variance");
	//	label	not set for rxs45_adcVariance
	rxs45_adcvariance_prop.set_unit("dBm");
	//	standard_unit	not set for rxs45_adcVariance
	//	display_unit	not set for rxs45_adcVariance
	//	format	not set for rxs45_adcVariance
	//	max_value	not set for rxs45_adcVariance
	//	min_value	not set for rxs45_adcVariance
	//	max_alarm	not set for rxs45_adcVariance
	//	min_alarm	not set for rxs45_adcVariance
	//	max_warning	not set for rxs45_adcVariance
	//	min_warning	not set for rxs45_adcVariance
	//	delta_t	not set for rxs45_adcVariance
	//	delta_val	not set for rxs45_adcVariance
	rxs45_adcvariance_prop.set_event_period("3000");
	
	rxs45_adcvariance->set_default_properties(rxs45_adcvariance_prop);
	rxs45_adcvariance->set_polling_period(3000);
	rxs45_adcvariance->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxs45_adcvariance->set_change_event(true, false);
	att_list.push_back(rxs45_adcvariance);

	//	Attribute : rxs45_expectedOnline
	rxs45_expectedOnlineAttrib	*rxs45_expectedonline = new rxs45_expectedOnlineAttrib();
	Tango::UserDefaultAttrProp	rxs45_expectedonline_prop;
	rxs45_expectedonline_prop.set_description("Indicates whether major component is expected online.  mcHealthStatus will be normal \nif this value is set to false and the device is not installed or offline.");
	//	label	not set for rxs45_expectedOnline
	//	unit	not set for rxs45_expectedOnline
	//	standard_unit	not set for rxs45_expectedOnline
	//	display_unit	not set for rxs45_expectedOnline
	//	format	not set for rxs45_expectedOnline
	//	max_value	not set for rxs45_expectedOnline
	//	min_value	not set for rxs45_expectedOnline
	//	max_alarm	not set for rxs45_expectedOnline
	//	min_alarm	not set for rxs45_expectedOnline
	//	max_warning	not set for rxs45_expectedOnline
	//	min_warning	not set for rxs45_expectedOnline
	//	delta_t	not set for rxs45_expectedOnline
	//	delta_val	not set for rxs45_expectedOnline
	rxs45_expectedonline_prop.set_event_rel_change("0.1");
	rxs45_expectedonline_prop.set_event_abs_change("0.1");
	
	rxs45_expectedonline->set_default_properties(rxs45_expectedonline_prop);
	//	Not Polled
	rxs45_expectedonline->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxs45_expectedonline->set_change_event(true, false);
	att_list.push_back(rxs45_expectedonline);

	//	Attribute : rxs45_healthState
	rxs45_healthStateAttrib	*rxs45_healthstate = new rxs45_healthStateAttrib();
	Tango::UserDefaultAttrProp	rxs45_healthstate_prop;
	rxs45_healthstate_prop.set_description("Major component health status");
	//	label	not set for rxs45_healthState
	//	unit	not set for rxs45_healthState
	//	standard_unit	not set for rxs45_healthState
	//	display_unit	not set for rxs45_healthState
	//	format	not set for rxs45_healthState
	//	max_value	not set for rxs45_healthState
	//	min_value	not set for rxs45_healthState
	//	max_alarm	not set for rxs45_healthState
	//	min_alarm	not set for rxs45_healthState
	//	max_warning	not set for rxs45_healthState
	//	min_warning	not set for rxs45_healthState
	//	delta_t	not set for rxs45_healthState
	//	delta_val	not set for rxs45_healthState
	rxs45_healthstate_prop.set_event_rel_change("0.1");
	rxs45_healthstate_prop.set_event_abs_change("0.1");
	
	{
		vector<string> labels;
		labels.push_back("NORMAL");
		labels.push_back("DEGRADED");
		labels.push_back("FAILED");
		rxs45_healthstate_prop.set_enum_labels(labels);
	}
	rxs45_healthstate->set_default_properties(rxs45_healthstate_prop);
	//	Not Polled
	rxs45_healthstate->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxs45_healthstate->set_change_event(true, false);
	att_list.push_back(rxs45_healthstate);

	//	Attribute : rxs45_hourCounter
	rxs45_hourCounterAttrib	*rxs45_hourcounter = new rxs45_hourCounterAttrib();
	Tango::UserDefaultAttrProp	rxs45_hourcounter_prop;
	rxs45_hourcounter_prop.set_description("Operational run time in hours");
	//	label	not set for rxs45_hourCounter
	rxs45_hourcounter_prop.set_unit("h");
	//	standard_unit	not set for rxs45_hourCounter
	//	display_unit	not set for rxs45_hourCounter
	//	format	not set for rxs45_hourCounter
	//	max_value	not set for rxs45_hourCounter
	//	min_value	not set for rxs45_hourCounter
	//	max_alarm	not set for rxs45_hourCounter
	//	min_alarm	not set for rxs45_hourCounter
	//	max_warning	not set for rxs45_hourCounter
	//	min_warning	not set for rxs45_hourCounter
	//	delta_t	not set for rxs45_hourCounter
	//	delta_val	not set for rxs45_hourCounter
	
	rxs45_hourcounter->set_default_properties(rxs45_hourcounter_prop);
	//	Not Polled
	rxs45_hourcounter->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(rxs45_hourcounter);

	//	Attribute : rxs45_supplyCurrent
	rxs45_supplyCurrentAttrib	*rxs45_supplycurrent = new rxs45_supplyCurrentAttrib();
	Tango::UserDefaultAttrProp	rxs45_supplycurrent_prop;
	rxs45_supplycurrent_prop.set_description("Major component supply current");
	//	label	not set for rxs45_supplyCurrent
	//	unit	not set for rxs45_supplyCurrent
	//	standard_unit	not set for rxs45_supplyCurrent
	//	display_unit	not set for rxs45_supplyCurrent
	//	format	not set for rxs45_supplyCurrent
	//	max_value	not set for rxs45_supplyCurrent
	//	min_value	not set for rxs45_supplyCurrent
	//	max_alarm	not set for rxs45_supplyCurrent
	//	min_alarm	not set for rxs45_supplyCurrent
	//	max_warning	not set for rxs45_supplyCurrent
	//	min_warning	not set for rxs45_supplyCurrent
	//	delta_t	not set for rxs45_supplyCurrent
	//	delta_val	not set for rxs45_supplyCurrent
	rxs45_supplycurrent_prop.set_event_period("3000");
	
	rxs45_supplycurrent->set_default_properties(rxs45_supplycurrent_prop);
	rxs45_supplycurrent->set_polling_period(3000);
	rxs45_supplycurrent->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxs45_supplycurrent->set_change_event(true, false);
	att_list.push_back(rxs45_supplycurrent);

	//	Attribute : rxs45_supplyVoltage
	rxs45_supplyVoltageAttrib	*rxs45_supplyvoltage = new rxs45_supplyVoltageAttrib();
	Tango::UserDefaultAttrProp	rxs45_supplyvoltage_prop;
	rxs45_supplyvoltage_prop.set_description("Major component supply voltage");
	//	label	not set for rxs45_supplyVoltage
	rxs45_supplyvoltage_prop.set_unit("V");
	//	standard_unit	not set for rxs45_supplyVoltage
	//	display_unit	not set for rxs45_supplyVoltage
	//	format	not set for rxs45_supplyVoltage
	//	max_value	not set for rxs45_supplyVoltage
	//	min_value	not set for rxs45_supplyVoltage
	//	max_alarm	not set for rxs45_supplyVoltage
	//	min_alarm	not set for rxs45_supplyVoltage
	//	max_warning	not set for rxs45_supplyVoltage
	//	min_warning	not set for rxs45_supplyVoltage
	//	delta_t	not set for rxs45_supplyVoltage
	//	delta_val	not set for rxs45_supplyVoltage
	rxs45_supplyvoltage_prop.set_event_period("3000");
	
	rxs45_supplyvoltage->set_default_properties(rxs45_supplyvoltage_prop);
	rxs45_supplyvoltage->set_polling_period(3000);
	rxs45_supplyvoltage->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxs45_supplyvoltage->set_change_event(true, false);
	att_list.push_back(rxs45_supplyvoltage);

	//	Attribute : rxs45_temperature
	rxs45_temperatureAttrib	*rxs45_temperature = new rxs45_temperatureAttrib();
	Tango::UserDefaultAttrProp	rxs45_temperature_prop;
	rxs45_temperature_prop.set_description("Device temperature");
	//	label	not set for rxs45_temperature
	rxs45_temperature_prop.set_unit("°C");
	//	standard_unit	not set for rxs45_temperature
	//	display_unit	not set for rxs45_temperature
	//	format	not set for rxs45_temperature
	//	max_value	not set for rxs45_temperature
	//	min_value	not set for rxs45_temperature
	//	max_alarm	not set for rxs45_temperature
	//	min_alarm	not set for rxs45_temperature
	//	max_warning	not set for rxs45_temperature
	//	min_warning	not set for rxs45_temperature
	//	delta_t	not set for rxs45_temperature
	//	delta_val	not set for rxs45_temperature
	rxs45_temperature_prop.set_event_period("3000");
	
	rxs45_temperature->set_default_properties(rxs45_temperature_prop);
	rxs45_temperature->set_polling_period(3000);
	rxs45_temperature->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	rxs45_temperature->set_change_event(true, false);
	att_list.push_back(rxs45_temperature);


	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(RxEmulatorClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulatorClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : RxEmulatorClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void RxEmulatorClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(RxEmulatorClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulatorClass::pipe_factory_before
	/*----- PROTECTED REGION ID(RxEmulatorClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulatorClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : RxEmulatorClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void RxEmulatorClass::command_factory()
{
	/*----- PROTECTED REGION ID(RxEmulatorClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulatorClass::command_factory_before
	//	Call command_factory for inherited class
	SEEmulatorBase_ns::SEEmulatorBaseClass::command_factory();



	//	Command Capture
	CaptureClass	*pCaptureCmd =
		new CaptureClass("Capture",
			Tango::DEV_SHORT, Tango::DEVVAR_LONGSTRINGARRAY,
			"Flag value start/stop (0/1)",
			"Long arg\n[0]: ack code\n\nString arg\n[0]: error/info description",
			Tango::OPERATOR);
	command_list.push_back(pCaptureCmd);

	//	Command ConfigureBand
	ConfigureBandClass	*pConfigureBandCmd =
		new ConfigureBandClass("ConfigureBand",
			Tango::DEV_SHORT, Tango::DEVVAR_LONGSTRINGARRAY,
			"Band id",
			"Long arg\n[0]: ack code\n\nString arg\n[0]: err/info description",
			Tango::OPERATOR);
	command_list.push_back(pConfigureBandCmd);

	//	Command SetEngineeringInterface
	SetEngineeringInterfaceClass	*pSetEngineeringInterfaceCmd =
		new SetEngineeringInterfaceClass("SetEngineeringInterface",
			Tango::DEV_VOID, Tango::DEVVAR_LONGSTRINGARRAY,
			"",
			"Long arg\n[0]: ack code\n\nString arg\n[0]: error/info description",
			Tango::OPERATOR);
	command_list.push_back(pSetEngineeringInterfaceCmd);

	//	Command SetExpectedOnline
	SetExpectedOnlineClass	*pSetExpectedOnlineCmd =
		new SetExpectedOnlineClass("SetExpectedOnline",
			Tango::DEVVAR_SHORTARRAY, Tango::DEVVAR_LONGSTRINGARRAY,
			"[0]: Major component enum (RXS123,RXS45,RXC)\n[1]: Flag value enable/disable (0/1)",
			"Long arg\n[0]: ack code\n\nString arg\n[0]: error/info description",
			Tango::OPERATOR);
	command_list.push_back(pSetExpectedOnlineCmd);

	//	Command SetSubElementMode
	SetSubElementModeClass	*pSetSubElementModeCmd =
		new SetSubElementModeClass("SetSubElementMode",
			Tango::DEV_ENUM, Tango::DEVVAR_LONGSTRINGARRAY,
			"Operational mode",
			"Long arg\n[0]: ack code\n\nString arg\n[0]: err/info description",
			Tango::OPERATOR);
	command_list.push_back(pSetSubElementModeCmd);

	//	Command SetNoiseSource
	SetNoiseSourceClass	*pSetNoiseSourceCmd =
		new SetNoiseSourceClass("SetNoiseSource",
			Tango::DEVVAR_LONGARRAY, Tango::DEVVAR_LONGSTRINGARRAY,
			"[0]: Start time of a new noise source\n[1]: Noise source period (Duty cycle: time fraction in [0,1] in which the \nnoise diode is turned on)\n[2]: Noise source on time (Overall period of a on/off cycle in seconds)\n[3]: Noise source off time",
			"Long arg\n[0]: ack code\n\nString arg\n[0]: error/info description",
			Tango::OPERATOR);
	command_list.push_back(pSetNoiseSourceCmd);

	//	Command Synchronise
	SynchroniseClass	*pSynchroniseCmd =
		new SynchroniseClass("Synchronise",
			Tango::DEV_VOID, Tango::DEVVAR_LONGSTRINGARRAY,
			"",
			"Long arg\n[0]: ack code\n\nString arg\n[0]: err/info description",
			Tango::OPERATOR);
	command_list.push_back(pSynchroniseCmd);

	//	Command SetAttenuation
	SetAttenuationClass	*pSetAttenuationCmd =
		new SetAttenuationClass("SetAttenuation",
			Tango::DEV_LONG, Tango::DEVVAR_LONGSTRINGARRAY,
			"Attenuation value",
			"Long arg\n[0]: ack code\n\nString arg\n[0]: Err/info description",
			Tango::OPERATOR);
	command_list.push_back(pSetAttenuationCmd);

	/*----- PROTECTED REGION ID(RxEmulatorClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulatorClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		RxEmulatorClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void RxEmulatorClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(RxEmulatorClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulatorClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		RxEmulatorClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void RxEmulatorClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		RxEmulator *dev = static_cast<RxEmulator *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(RxEmulatorClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	RxEmulatorClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : RxEmulatorClass::get_attr_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *RxEmulatorClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(RxEmulatorClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	RxEmulatorClass::Additional Methods
} //	namespace
