/*----- PROTECTED REGION ID(SPFEmulator.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        SPFEmulator.cpp
//
// description : C++ source for the SPFEmulator class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               SPFEmulator are implemented in this file.
//
// project :     SPFEmulator
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <SPFEmulator.h>
#include <SPFEmulatorClass.h>

/*----- PROTECTED REGION END -----*/	//	SPFEmulator.cpp

/**
 *  SPFEmulator class description:
 *    Emulator for SPF sub-element
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//================================================================

//================================================================
//  Attributes managed is:
//================================================================
//================================================================

namespace SPFEmulator_ns
{
/*----- PROTECTED REGION ID(SPFEmulator::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	SPFEmulator::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : SPFEmulator::SPFEmulator()
 *	Description : Constructors for a Tango device
 *                implementing the classSPFEmulator
 */
//--------------------------------------------------------
SPFEmulator::SPFEmulator(Tango::DeviceClass *cl, string &s)
 : SEEmulatorBase(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(SPFEmulator::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	SPFEmulator::constructor_1
}
//--------------------------------------------------------
SPFEmulator::SPFEmulator(Tango::DeviceClass *cl, const char *s)
 : SEEmulatorBase(cl, s)
{
	/*----- PROTECTED REGION ID(SPFEmulator::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	SPFEmulator::constructor_2
}
//--------------------------------------------------------
SPFEmulator::SPFEmulator(Tango::DeviceClass *cl, const char *s, const char *d)
 : SEEmulatorBase(cl, s, d)
{
	/*----- PROTECTED REGION ID(SPFEmulator::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	SPFEmulator::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : SPFEmulator::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void SPFEmulator::delete_device()
{
	DEBUG_STREAM << "SPFEmulator::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(SPFEmulator::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	SPFEmulator::delete_device

	if (Tango::Util::instance()->is_svr_shutting_down()==false  &&
		Tango::Util::instance()->is_device_restarting(device_name)==false &&
		Tango::Util::instance()->is_svr_starting()==false)
	{
		//	If not shutting down call delete device for inherited object
		SEEmulatorBase_ns::SEEmulatorBase::delete_device();
	}
}

//--------------------------------------------------------
/**
 *	Method      : SPFEmulator::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void SPFEmulator::init_device()
{
	DEBUG_STREAM << "SPFEmulator::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(SPFEmulator::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	SPFEmulator::init_device_before
	
	if (Tango::Util::instance()->is_svr_starting() == false  &&
		Tango::Util::instance()->is_device_restarting(device_name)==false)
	{
		//	If not starting up call init device for inherited object
		SEEmulatorBase_ns::SEEmulatorBase::init_device();
	}
	//	No device property to be read from database
	
	/*----- PROTECTED REGION ID(SPFEmulator::init_device) ENABLED START -----*/
	
	//	Initialize device
	
	/*----- PROTECTED REGION END -----*/	//	SPFEmulator::init_device
}


//--------------------------------------------------------
/**
 *	Method      : SPFEmulator::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void SPFEmulator::always_executed_hook()
{
	DEBUG_STREAM << "SPFEmulator::always_executed_hook()  " << device_name << endl;
	/*----- PROTECTED REGION ID(SPFEmulator::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	SPFEmulator::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : SPFEmulator::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void SPFEmulator::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "SPFEmulator::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(SPFEmulator::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SPFEmulator::read_attr_hardware
}


//--------------------------------------------------------
/**
 *	Method      : SPFEmulator::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void SPFEmulator::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(SPFEmulator::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	SPFEmulator::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : SPFEmulator::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void SPFEmulator::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(SPFEmulator::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	SPFEmulator::add_dynamic_commands
}

/*----- PROTECTED REGION ID(SPFEmulator::namespace_ending) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	SPFEmulator::namespace_ending
} //	namespace
