/*----- PROTECTED REGION ID(PointingMgrStateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        PointingMgrStateMachine.cpp
//
// description : State machine file for the PointingMgr class
//
// project :     Pointing Manager
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <PointingMgr.h>

/*----- PROTECTED REGION END -----*/	//	PointingMgr::PointingMgrStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace PointingMgr_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : PointingMgr::is_TrackAzEl_allowed()
 *	Description : Execution allowed for TrackAzEl attribute
 */
//--------------------------------------------------------
bool PointingMgr::is_TrackAzEl_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for TrackAzEl command.
	/*----- PROTECTED REGION ID(PointingMgr::TrackAzElStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	PointingMgr::TrackAzElStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(PointingMgr::PointingMgrStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	PointingMgr::PointingMgrStateAllowed.AdditionalMethods

}	//	End of namespace
